### PR TITLE
Update default image for the application

### PR DESCRIPTION
**Pull request by lmcglohon**
@cdibella Can you review this for me?

### CODE REVIEW

**Comment by cdibella** [comment]
@lmcglohon Is the intent to just change this on the PDF? I'm thinking this - https://github.com/archivesspace/archivesspace/blob/5e1ca66f1f04f142f2695024efb7200825046325/frontend/app/views/site/_branding.html.erb  - is the more recognizable place it should be changed. (But maybe you're doing that on a separate commit.)

Also, I'm wondering if there's anything for sizing the image in the PDF. I think the new one might be larger than the previous one. Ideally for both the staff interface and the PDF we'd like the new image to take up no more real estate than the old one.

**Comment by sdm7g** [comment]
Also, see this thread in ASpace mailing list:
http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2017-August/005054.html

I had tried changing that line to use repo logo/branding image if there was one for repository:
`<div class="logo"><%= image_tag( record.resolved_repository['image_url'] || asset_url("Aspace-logo.png") ) %></div>`
but the CSS doesn't handle different sized images well at all. It may cause text supposed to be at the bottom of first page to overwrite text on the top of the next page. ( It did in several of the images I tested, but I haven't tried this  image. )
I was going to get back to debugging this asap:
Dumping the html + css to a temp file to inspect the css before it transforms to PDF.

**Comment by lmcglohon** [comment]
@cdibella I think this is ready now :)

**Comment by cdibella** [comment]
Looks good!

**Pull request merged**
