### PR TITLE
Ar 1750 filter tidyup

### PR DESCRIPTION
**Pull request by jambun**

### CODE REVIEW

**Comment by marktriggs** [comment]
Looking good to me.  Don't forget to i18n the 'more' and 'less' labels so we can have más o menos!

**Comment by jambun** [comment]
Ah yes  - will do. Thanks

**Comment by jambun** [comment]
done - even maintaining the French translation in English meme.

**Comment by jambun** [comment]
One more commit following a clarification of the requirements.

**Comment by marktriggs** [comment]
:passenger_ship:

**Pull request merged**
