### PR TITLE
Always keep the display name when deduplicating non-authorized names

### PR DESCRIPTION
**Pull request by marktriggs**
Howdy,

Today I noticed a small but long-standing bug that allows agents to get into a weird state as a result of combining duplicate names.  Gory details and a fix below!

## Description

The incoming list of agent names is processed to remove duplicates prior to being saved, so a set like this:

     names: [{primary_name: "hello", authorized: true, is_display_name: true},
             {primary_name: "duplicate", authorized: false, is_display_name: false},
             {primary_name: "duplicate", authorized: false, is_display_name: false}]

Is collapsed to:

     names: [{primary_name: "hello", authorized: true, is_display_name: true},
             {primary_name: "duplicate", authorized: false, is_display_name: false}]

This can cause problems if you see input like this:

     names: [{primary_name: "hello", authorized: true,  is_display_name: false},
             {primary_name: "hello", authorized: false, is_display_name: true}]

The deduplication code just naively takes whichever name it sees first, but in this case the duplicate was marked as the display name. Collapsing to:

     names: [{primary_name: "hello", authorized: true,  is_display_name: false}]

leaves us without a display name at all, and then viewing the resulting agent record throws an error.

This commit refines the behavior to the following:

  * We always keep the authorized name

  * If two names are the same, we keep whichever was marked as the display name (if neither was, we can choose either)

  * If a duplicate of the authorized name was marked as the display name, the authorized name becomes the display name

## Related JIRA Ticket or GitHub Issue

None

## Motivation and Context

Hopefully covered above!

## How Has This Been Tested?

I've added two new test cases to the backend tests to cover this bug.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lmcglohon** [comment]
Not sure why tests are failing on this one.

**Comment by mark-cooper** [comment]
Hi @marktriggs 

Sorry this has taken a while for me to get to, it is very much appreciated 😄 

It all looks good to me!

The test issue appears to be pre-existing for `turns off autogen if slug is blank`.

Firstly, it's passing in master because `is_slug_auto` is already 0 before it is updated. So I modified the spec:

```
    it "turns off autogen if slug is blank" do
        AppConfig[:auto_generate_slugs_with_id] = true

        agent_name_person = build(:json_name_person, :authority_id => rand(100000).to_s)
        agent_person = AgentPerson.create_from_json(
        build(:json_agent_person,
            :is_slug_auto => true,
            :names => [agent_name_person])
        )
        expect(agent_person[:is_slug_auto]).to eq(1)
        agent_person.update(:slug => "")
        expect(agent_person[:is_slug_auto]).to eq(0)
    end
```

It passes in the branch with these changes which seems to conform to what is expected based on the slug handling code in `ASModel_sequel.rb`. @marktriggs do you want to try adding this to your branch so we can merge with the tests (hopefully) passing? Or would you prefer for us to merge as is and we'll fix the tests later?

**Comment by marktriggs** [comment]
Hey @mark-cooper,

No worries--good to hear from you :)  I've merged your updated test into my branch and it seemed to run happily.  Hopefully the Travis gods will be appeased...

**Comment by mark-cooper** [comment]
Awesome, thx! And it looks like The Capricious One has been appeased for the time being so we're good to go here 👍

**Pull request merged**
