### PR TITLE
Upgrade Bootstrap to 3.2 and many attendant changes in one big commit

### PR DESCRIPTION
**Pull request by quoideneuf**
replace bootstrap 2 with bootstrap 3

bump less compiler

replace span* with col-md-*

global search and replace, and rewrite navbar

more tweaks to layout, wrap everything in a div to center it

first pass resetting nav buttons etc

first pass at basic information form

update jquery.scrollTo to 1.4.14

update bootstrap scrollspy and remove patched version

first pass at BS3 subrecords and linkers; upgrade combobox and scrolling libraries

resource edit form fixes: date and other level

upgrade form error and warning alerts

font-based glyphicons

another round of bootstrap 3.x upgrades...almost there

selenium passing

cleanup and final tweaks

### CODE REVIEW

**Comment by quoideneuf** [comment]
Upgrades the bootstrap library as well as several JS libraries in the frontend application.

There will likely be some kinks to work out over the next few weeks, especially for Firefox and IE, but assuming the tests pass I recommend that the PR is merged and the issues get worked out in separate PRs.

**Comment by quoideneuf** [comment]
@cfitz  - any concerns about this? If not I'll go ahead and merge.

**Comment by cfitz** [comment]
been going over this this AM. looking good...maybe i'll send something out to the list?

**Comment by quoideneuf** [comment]
@cfitz - I think the auto merge option disappeared because I did the same thing @mst did with the breadcrumbs. Let me know if you want me to rebase and resubmit.

**Pull request merged**
