### PR TITLE
set migrate_to_container_management param to true(?)

### PR DESCRIPTION
**Pull request by quoideneuf**
As the config-defaults is now, it will raise a "No value for config parameter" error. I set it to true, not sure if that's right. Is there actually any way to opt out of the new container management data model anyway?

### CODE REVIEW

**Comment by mark-cooper** [comment]
@archivesspace/archivesspace-program-staff 

If possible it would be great to not require a config setting toggle for the upgrade. Haven't looked at any code at all but it raises the question: what happens if you don't set to true, and what happens if you forget to flip to false?

If the migration to the new container model can happen invisibly, as per the normal db migrations path, that's obviously much better for site admins and maintainers.

**Comment by bdwestbrook** [comment]
I am not seeing (instincts) the need for a choice here.  When using a plugin yes, but not this integrated functionality.  There seem to be too many gains for any org to what to stay with the old model.

Brad

**Comment by cfitz** [comment]
Hi, 
Sorry about this. Had it set in my local config and didn't notice that it was not set at all.

In regards to the update, it can't happen as a normal migration because it was written to use the REST API rather than Sequel. So, the backend has to be running. 
Any ideas how this could be run automatically without it running everytime aspace starts?

**Comment by mark-cooper** [comment]
Not looked closely by any means so apologies if not helpful:

https://github.com/archivesspace/archivesspace/blob/master/backend/app/main.rb#L208-L212

If instead of checking for a config setting there was a check for "something" :smile: that would indicate whether the migration was necessary, could that work? Perhaps something roughly like adding a table with a value to indicate whether the migration was processed which is checked for on startup?

Whatever it takes to get the human involvement and config flipping out would be great :smile:

**Comment by cfitz** [comment]
Yeah, I haven't pulled this in yet because there's been hints that having this not run as a startup thingy would be more ideal. The way this "migration" was written uses the API, which has downsides ( especially since it breaks previous practice ), it actually is not a bad idea since you get to use model validations to see you're not shooting yourself in the foot. 

So..we could:
1) keep this as is ( and how the plugin was written ) 
2) have a separate script people run after the backed has started
3) move this to a job that people can run from the frontend
4) translate all this into a traditional Sequel DB migrations ( and bring it in line with the standard upgrade process )

I actually think #3 is maybe a good idea, since that would give us a way to provide output to the archivists. However, this will probably require work..

**Comment by cfitz** [comment]
So, it sounds like we are going to:

1) Have the default be true
2) add something to the database that tracks if the migration has been run
3) document that this is happening.

**Comment by quoideneuf** [comment]
That sounds good to me, but f we're tracking whether the migration has been run in the database, do we need the Config value any more?

**Comment by bdwestbrook** [comment]
A little more than that, Chris:


1)      Have the default be “true”


2)      Provide session message indicating what is about to happen and notifying people that after the container migration is complete, they need to set the migration command to “false”



3)      Provide documentation / guidelines for knowing when the container migration is complete and for extracting container data warnings and using them to correct problems in ArchivesSpace due to the container migration



4)      Add “trace” in data set that container migration was done and provide alert that container migration was done and need not be done again.  (How does this apply to instances starting with the new container functionality intack, i.e. that do not have / did not need to migrate legacy container data?)

**Comment by cfitz** [comment]
Feature request here :  https://archivesspace.atlassian.net/browse/AR-1371

**Pull request closed without merging**
