### PR TITLE
ANW-930: Option for preferences to set locale

### PR DESCRIPTION
**Pull request by mark-cooper**
Adds option to set language (locale) using preferences for staff UI only.

### CODE REVIEW

**Comment by lmcglohon** [comment]
@mark-cooper I can't get the backend tests to run locally. I am getting this error: 
An error occurred while loading ./spec/asmodel_object_graph_spec.rb.
     [java] Failure/Error: JSONModel::init(:client_mode => true, :strict_mode => true,
     [java] 
     [java] Errno::ECONNREFUSED:
     [java]   Connection refused - Failed to open TCP connection to localhost:2999 (Connection refused - connect(2) for "localhost" port 2999)
 
I wonder if it is the way the spec_helper is set up - here: https://github.com/archivesspace/archivesspace/blob/bc675bc12b72f6fb7818aae646958c80d54ff4de/backend/spec/spec_helper.rb#L89-#L94?

**Comment by mark-cooper** [comment]
@lmcglohon I'll take a look!

**Comment by lmcglohon** [comment]
@mark-cooper Interesting. That definitely points in a particular direction. I look at it some more.

**Comment by mark-cooper** [comment]
@lmcglohon have to switch gears to cspace so don't have time to pursue it further for a couple of hours but I think the issue is the HTTP request. The `defaults.rb` is loaded via `eval` and wants to make a request -- the error "connection refused" points to solr not being available. Maybe best to remove the http request and load from a file? It's looking for json but may be possible to get the same info out of `schema.xml` (transform to json or just parse xml for same stuff)?

**Comment by mark-cooper** [comment]
Will make new PR to master.

**Pull request closed without merging**
