### PR TITLE
update ant jars to 1.9.6 and add if/unless namespace

### PR DESCRIPTION
**Pull request by sdm7g**
Issue:  https://github.com/archivesspace/archivesspace/issues/303

This patch just updates ant and adds if/unless namespace to build.xml. 
It doesn't (yet) modify the build in any way.

### CODE REVIEW

**Comment by sdm7g** [comment]
Added conditional local build to build a custom deployment zip file. If `local_build` is true, for example:
`./build/run dist -Dversion=local -Dlocal_build=true`  zip file will include:
*   mysql connector ( if it is present in common/lib )
*  append common/config/config.rb (if it exists) to  output archivesspace/config/config.rb 
*  ALL plugins in plugin directory 

ready to unzip  and deploy without any further configuration.

**Comment by mark-cooper** [comment]
Is there a potential license issue with allowing the mysql connector to be packaged using a process supplied by the project? Dunno, but worth double checking:

"ArchivesSpace requires the MySQL Connector for Java, which must be downloaded separately because of its licensing agreement."

Otherwise, my 2 cents is ambivalence towards the "local build" functionality. There are many, many ways to handle deployments and the build tools are intended for developers not sysadmins. "It doesn't (yet) modify the build in any way." hints at feature creep =)

At the very least, if the "local build" is going to be adopted, it requires some documentation otherwise it is basically solving a use case for a single user. Good topic for TAC? :wink:

**Comment by cfitz** [comment]
Hi,
Hm, yes maybe a good discussion for the TAC. Or maybe at the dev meetup
next month.

There was some recent weirdness with a newer version of Bundler that was
causing the app not to be able to find the connector in the lib directory.
Essentially the quick fix was to move the mysql gem to test, because this
was only a problem with the packaged app.

I do know we are not supposed to package the mysql connector because out
license ( ECL 2.0 ) is not on Oracle's "FOSS License Exception" list  (
https://www.mysql.com/about/legal/licensing/foss-exception/ ).

We can revisit all of this for the next release...
b,chris.

**Comment by quoideneuf** [comment]
I think I agree with @mark-cooper - If the idea is just to make it easier to have a local flavored build, why have a local build file that inherits from the master?

**Comment by sdm7g** [comment]
Modification of the build could definitely use some more discussion. 
There shouldn't be any problem with just updating the ant jars as originally proposed, however. 
This would just make it easier to add local customizations. 
I'm happy to withdraw the request for more specific changes pending further discussion. 

The issue is that I find the documented manual method of deployment too error prone. This is my current solution, but I'm open to finding a better way. 

> I think I agree with @mark-cooper - If the idea is just to make it easier to have a local flavored build, why not just have a local build file that inherits from the master?

Everything is done by one monolithic `build-zip` target. My previous method was to copy and edit this target in a separate 'mybuild.xml' file, but it had to be redone when build.xml was recently updated. build-zip could be refactored so that it calls other targets that could be overridden and specialized.  (  package-plugins and build-config targets for example. ) 
Another alternative would be to go ahead and perform the standard build-zip , and then modify the resulting zip file after the fact.

**Comment by quoideneuf** [comment]
@sdm7g - is the main issue you're having just adding content to the zip? Would it help if we moved the deletion of the target directory to the "dist" task? that way maybe you could write your own dist task and insert a task to add your content before calling the core dist task??

**Pull request closed without merging**
