### PR TITLE
Fix public errors

### LINKED ISSUE #1090: Error call the repository page (Public Interface)
Hello!

I cought an error if I call the repository page of a fresh installed system. Here the log

```
INFORMATION: [collection1] webapp= path=/select params={csv.escape=\&start=0&sort=repo_sort+asc&fq=-exclude_by_default:true&fq=publish:true&rows=100&q=primary_type:repository&defType=edismax&qf=four_part_id^3+title^2+finding_aid_filing_title^2+fullrecord&pf=four_part_id^4&csv.header=true&csv.encapsulator="&wt=json&facet=true} hits=0 status=0 QTime=1 
D, [2018-01-13T05:56:13.213318 #9127] DEBUG -- : Thread-3368: Responded with [200, {"Content-Type"=>"application/json", "Cache-Control"=>"private, must-revalidate, max-age=0", "Content-Length"=>"226"}, ["{\"page_size\":100,\"first_page\":1,\"last_page\":0,\"this_page\":1,\"offset_first\":1,\"offset_last\":0,\"total_hits\":0,\"results\":[],\"facets\":{\"facet_queries\":{},\"facet_fields\":{},\"facet_dates\":{},\"facet_ranges\":{},\"facet_intervals\":{}}}\n"]]... in 36ms
Jan 13, 2018 5:56:13 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFORMATION: D, [2018-01-13T05:56:13.215151 #9127] DEBUG -- : [c5910b18-b30e-43bb-a8e2-7a17f4166483] TOTAL HITS: 0, last_page: 0

Jan 13, 2018 5:56:13 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFORMATION: I, [2018-01-13T05:56:13.223467 #9127]  INFO -- : [c5910b18-b30e-43bb-a8e2-7a17f4166483]   Rendering repositories/index.html.erb within layouts/application

Jan 13, 2018 5:56:13 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFORMATION: I, [2018-01-13T05:56:13.257303 #9127]  INFO -- : [c5910b18-b30e-43bb-a8e2-7a17f4166483]   Rendered shared/_pagination.html.erb (30.1ms)

Jan 13, 2018 5:56:13 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFORMATION: I, [2018-01-13T05:56:13.261202 #9127]  INFO -- : [c5910b18-b30e-43bb-a8e2-7a17f4166483]   Rendered repositories/index.html.erb within layouts/application (35.8ms)

Jan 13, 2018 5:56:13 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFORMATION: I, [2018-01-13T05:56:13.270102 #9127]  INFO -- : [c5910b18-b30e-43bb-a8e2-7a17f4166483] Completed 500 Internal Server Error in 157ms

Jan 13, 2018 5:56:13 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFORMATION: F, [2018-01-13T05:56:13.283787 #9127] FATAL -- : [c5910b18-b30e-43bb-a8e2-7a17f4166483]   

Jan 13, 2018 5:56:13 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFORMATION: F, [2018-01-13T05:56:13.285665 #9127] FATAL -- : [c5910b18-b30e-43bb-a8e2-7a17f4166483] ActionView::Template::Error (undefined method `pages' for nil:NilClass):

Jan 13, 2018 5:56:13 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFORMATION: F, [2018-01-13T05:56:13.287706 #9127] FATAL -- : [c5910b18-b30e-43bb-a8e2-7a17f4166483]     1: <% if pager.pages.last > 1 %>
[c5910b18-b30e-43bb-a8e2-7a17f4166483]     2: <div id="paging">
[c5910b18-b30e-43bb-a8e2-7a17f4166483]     3:   
[c5910b18-b30e-43bb-a8e2-7a17f4166483]     4:   <ul class="pagination">

Jan 13, 2018 5:56:13 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFORMATION: F, [2018-01-13T05:56:13.289254 #9127] FATAL -- : [c5910b18-b30e-43bb-a8e2-7a17f4166483
```

What is to do or what happend at the system side? 

Thanks in advance for an answer or hint!

### PR DESCRIPTION
**Pull request by cfitz**
Fixes #1090 and adds an error page when the Public UI cannot connect to the backend.
Tries to DRY out the exception rescue bits by moving it to the application controller

You might not see some of these pages in development unless you change the development.rb to

```
config.consider_all_requests_local = false
```

### CODE REVIEW

**Comment by cfitz** [comment]
Hi,

Sure,  I removed that logger line..The PUI has a few things that probably need to be looked at.

I just tried it out in v2.3.0 and am still seeing this.  Just start a new instance, go to the PUI, and click "Repository" and you'll see the issue, I think.

**Comment by pobocks** [comment]
So, going to Repository, on a brand new (guaranteed bc Derby), here's what I see:

repositories

I think somewhere it's doing a count and not discounting the global repo, but I haven't found it yet.  

Thus, the "no repositories" code/templates are unreachable.  I think it'd be fine to merge this if we make an issue for that, or if you can find and fix it - whichever you want to do.

**Comment by cfitz** [comment]
Hm, ok weird. I just downloaded  v2.3.0, started it, went to http://localhost:8081/repositories  and got this: 

image

With the message:
F, [2018-02-20T17:49:43.197416 #19404] FATAL -- : [ad3571f4-acca-4b99-bff8-606126c0d786] ActionView::Template::Error (undefined method `pages' for nil:NilClass):
F, [2018-02-20T17:49:43.197781 #19404] FATAL -- : [ad3571f4-acca-4b99-bff8-606126c0d786]     1: <% if pager.pages.last > 1 %>
[ad3571f4-acca-4b99-bff8-606126c0d786]     2: <div id="paging">
[ad3571f4-acca-4b99-bff8-606126c0d786]     3:   
[ad3571f4-acca-4b99-bff8-606126c0d786]     4:   <ul class="pagination">
F, [2018-02-20T17:49:43.197886 #19404] FATAL -- : [ad3571f4-acca-4b99-bff8-606126c0d786]   
F, [2018-02-20T17:49:43.197994 #19404] FATAL -- : [ad3571f4-acca-4b99-bff8-606126c0d786] app/views/shared/_pagination.html.erb:1:in `_app_views_shared__pagination_html_erb___460480519_2292'
[ad3571f4-acca-4b99-bff8-606126c0d786] app/views/repositories/index.html.erb:5:in `_app_views_repositories_index_html_erb___2118834944_2290'
[ad3571f4-acca-4b99-bff8-606126c0d786] app/controllers/repositories_controller.rb:45:in `index'

Maybe the indexer is starting up before the global repository gets made, but the global repository is hidden is I'm not sure it's indexed?

**Comment by pobocks** [comment]
Hmmm. Wait, I may be misunderstanding more generally - what's the precise state of code you're testing? I've been testing the tip of this branch, just as is - I've been testing it in the devserver env rather than building, because it seemed unlikely to matter for this specific thing.

**Comment by cfitz** [comment]
Yeah, sorry, I described the problem poorly..."Fix public errors" is a shit name for a PR. 

The main problem is ( I think ) the same one #1090 . To replicate, it's download a fresh release, start it, and go to the PUI /repositories page. An error is thrown because no results were returned from Solr and the @pager is nil, but the pagination partial expects a paging object.

To fix that, I added copied what the other controllers where doing ( raise a NoResultsError if Solr doesn't return anything ), but moved all that to a rescue_from in the ApplicationController ( rather than manually rescuing in all the controllers )

I also added a CYA check that the pager object is not nil in the pagination partial. 

Lastly, I added some additional rescue_from exceptions  ( LoginFailed and RequestFailed ) so that if the aspace client can't connect to the backend, an error page is displayed.

I think this fixes that, but it's been a while since i've looked at this...but also you have to make sure that Solr is totally empty when you start it up. Also I think in development mode I had to change the config to consider_all_requests_local to true ( i think? )

**Comment by pobocks** [comment]
Oh, that makes sense, since I don't think I cleared the indexer...

I'll test this ASAP.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pobocks** [comment]
Oh, that makes sense. I'll try and give this a test asap.

**Comment by cfitz** [comment]
:tada: 
And sorry about the confusion...  I think I write most of my aspace PRs while I'm on the train, so things might not be very clear sometimes!

**Comment by pobocks** [comment]
Ha ha, no worries, I used to do the same before I started taking the more populated train so I could ride in with my wife.

**Pull request merged**
