### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by lmcglohon**

### CODE REVIEW

**Comment by lorawoodford** [comment]
@lmcglohon Tests are failing for me when I check this out locally.  Could be user error on this end, but here's what I've got.

[testlog.txt](https://github.com/archivesspace/archivesspace/files/1790956/testlog.txt)

**Comment by lmcglohon** [comment]
@lorawoodford I can't replicate the issue you are having. There is still some work to do, however.  I'll ping you when it is ready

**Comment by lmcglohon** [comment]
@lorawoodford Got time to merge this in the next couple of days?

**Comment by lorawoodford** [comment]
@lmcglohon Just want to confirm that I haven't forgotten about this, but I've had a heck of a time getting reliable enough wifi on the train to test this out.  Still plugging.

**Comment by lorawoodford** [comment]
So I'm still not personally able to get the tests to run, but I'm gonna go ahead an merge this anyway since I've been holding you up.

In particular, I'm now getting this error when attempting to run the tests:

`Waiting for http://localhost:3434 (#<Errno::ECONNREFUSED: Connection refused - Failed to open TCP connection to localhost:3434 (Connection refused - connect(2) for "localhost" port 3434)>)`

**Comment by lorawoodford** [comment]
This was user error!  All appears to be working on this end now.  Deleting branch.

**Pull request merged**
