### PR TITLE
i18n updates

### PR DESCRIPTION
**Pull request by nebulon42**
## Description

Corrected weird translation when session expired.
Added missing / corrected German translations.
Added missing "Occupations" translation use.
Reworked modal translations.
Translated aria-label strings.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by nebulon42** [comment]
Thanks, I updated a test and will check if there is still something left to do when the tests did complete (which takes a while).

**Comment by nebulon42** [comment]
There is still one failure but I don't see how my changes would affect the system information test. I did touch the file `403.html.erb` but that particular part stayed the same.

**Comment by quoideneuf** [comment]
> There is still one failure but I don't see how my changes would affect the system information test. I did touch the file `403.html.erb` but that particular part stayed the same.

@nebulon42 - The change to `403.html.erb` did indeed cause that test to break:

```diff
-    <p><%= I18n.t("login.login_expired_link", :link => link_to(I18n.t("login.login"), :controller => :welcome, :action => :index, :login => true)).html_safe %></p>
+    <p><%= I18n.t("login.login_expired_link"), :controller => :welcome, :action => :index, :login => true)).html_safe %></p>

```
If you look closely, the `:controller` and `:action` arguments actually belong to the `link_to` method, so with that taken out there is an extra `)` and the template raises an error.

There is a bigger issue with making that change. The existing application passes the `link` into the translation string so that you get this effect:

image

I can see how this will not work for German and other languages where the syntax is different. Perhaps we could change to something like:

"Please Sign in Again: Click here to sign in." and that could be done in YAML like this:

```yaml
login:
  login_exired_link: Please sign in again: %{click_here_link}
  click_here_link: Click here to sign in
```

**Comment by nebulon42** [comment]
Yes, you are right, thanks. Not sure why I haven't seen that. I have now replaced the link_to with url_for which I think is a bit cleaner than your original proposal as this saves us the additional link text.

**Review by quoideneuf — APPROVED** [review]
ausgezeichnet

**Pull request merged**
