### PR TITLE
Anw 1021 pdf generate option

### PR DESCRIPTION
**Pull request by markowitzj-si**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by lorawoodford** [comment]
Thanks for this @markowitzj-si . Looks alright, so I'm handing this over to a core committer for review. In an ideal world, we'd want to see [one commit per PR](http://ndlib.github.io/practices/one-commit-per-pull-request/#git-rebase-interactive) to keep the history tidy, but I understand if you cannot return to this in a timely fashion to do so.

**Comment by sdm7g** [comment]
When I try. out this patch, I'm seeing that initially include-unpublished is unchecked in the form, but the action. link has ?include-unpublished=true and that's what the batch job gets. If the checkbox is clicked once or more times, then the. box and the URL get back in sync, but initially they don't match. 
( I'll double check this to make sure what I think I'm seeing is correct! )

**Comment by sdm7g** [comment]
I think that one additional line is needed so that the the initial action and the form are in sync. i.e. set include_unpublished = false to match unchecked state. @markowitzj-si  if you can add that line and commit to your branch, I will merge. 

```
diff --git a/frontend/app/views/resources/_toolbar.html.erb b/frontend/app/views/resources/_toolbar.html.erb
index 9cddab212..9e2875e76 100644
--- a/frontend/app/views/resources/_toolbar.html.erb
+++ b/frontend/app/views/resources/_toolbar.html.erb
@@ -53,11 +53,11 @@
         <% if job_types['print_to_pdf_job']['create_permissions'].reject{|perm| user_can?(perm)}.empty? %>
 
           <li class="dropdown-submenu">
-            <%= link_to I18n.t("actions.print_to_pdf"), {:controller => :exports,  :action => :print_to_pdf, :id => @resource.id, :include_unpublished => true}, :id => 'print-to-pdf-link', :target => "_blank" %>
+            <%= link_to I18n.t("actions.print_to_pdf"), {:controller => :exports,  :action => :print_to_pdf, :id => @resource.id, :include_unpublished => false }, :id => 'print-to-pdf-link', :target => "_blank" %>
             <div class="dropdown-menu">
               <fieldset>
                 <label class="checkbox" for="include-unpublished-pdf">
-                  <input type="checkbox" id="include-unpublished-pdf" checked="true" onchange="$('#print-to-pdf-link').attr('href', '<%= url_for :controller => :exports,  :action => :print_to_pdf, :id => @resource.id %>?include_unpublished=' + $(this).prop('checked'))" />
+                  <input type="checkbox" id="include-unpublished-pdf" onchange="$('#print-to-pdf-link').attr('href', '<%= url_for :controller => :exports,  :action => :print_to_pdf, :id => @resource.id %>?include_unpublished=' + $(this).prop('checked'))" />
                   <%= I18n.t("export_options.include_unpublished") %>&#160;
                 </label>
               </fieldset>
```

**Comment by sdm7g** [comment]
@lorawoodford  Or I can merge this patch and add that one additional line in another pull req. (?)

**Comment by lorawoodford** [comment]
If you don't mind, @sdm7g , yes, go ahead and do that.  I'll merge your follow-on PR as soon as I see it come in.

**Pull request merged**
