### PR TITLE
PDF export needs update for EAD3 too

### PR DESCRIPTION
**Pull request by mark-cooper**

### CODE REVIEW

**Comment by mark-cooper** [comment]
I've mirrored the current way it's being done ... but if (as I believe is the case) PDF is not possible from EAD3 then simply setting the final parameter to false for `generate_ead` may be preferable.

**Comment by fordmadox** [comment]
@mark-cooper :  right, there's no way that the current EAD to PDF approach within the staff interface will work if the fifth parameter for ead3 = true is included.  The current approach rightly uses the EAD2002 namespace (e.g. https://github.com/archivesspace/archivesspace/blob/master/stylesheets/as-ead-pdf.xsl#L4), not the EAD3 namespace, and not any namespace whatsoever.  Even if it didn't, there are other structural and naming changes in EAD3 that wouldn't allow an EAD2002-to-PDF transformation to work perfectly.   PDF is possible from EAD3, of course, but just not with the current ASpace stylesheets :)

All that said, is there a way to update how things work here so that adding additional, optional parameters in the future wouldn't break things?

**Comment by alexduryee** [comment]
@fordmadox I'm not quite clear what you mean by updating the controller options without breaking things - do you have an example of what you're looking for?

**Comment by mark-cooper** [comment]
"Just so I'm clear - since the PDF XSL does not support EAD3 yet, this PR is just to prepare the controller for when the XSL is updated?"

Note quite - the primary need is because without it the pdf export is broken because `generate_ead` is not receiving the correct no. of parameters. As it is it should (likely) eventually work with ead3 to pdf conversion when that is implemented, so I think it's fine this way.

"All that said, is there a way to update how things work here so that adding additional, optional parameters in the future wouldn't break things?"

With some refactoring sure ... how deep do you want to dig that hole? 😄

**Comment by alexduryee** [comment]
@mark-cooper Sure thing - the PR looks good to me.  I'll merge it in.

**Pull request merged**
