### PR TITLE
ANW-1690 ensure record link after +1 event

### PR DESCRIPTION
**Pull request by donaldjosephsmith**
Adds the record URI and type to the "plus 1" button parameters so the record will again be linked automatically on the new event form.

### CODE REVIEW

**Review by brianzelip — APPROVED** [review]
Nice work @donaldjosephsmith! The test works well, I think waiting on the aria attribute to show up is a good approach.

As an aside, it bugs me that in the tests some DOM elements have to be grabbed by near-anonymous selectors like `div.resource`. I've been slowly adding unique identifiers to markup, often via`data-*` attributes rather than classes.

**Comment by cdibella** [comment]
@brianzelip @donaldjosephsmith Was this one ready to merge? The JIRA is marked Ready for Testing and from Brian's comment above it sounds like it's good to go, but it's still open and I'm still seeing the original bug on the test server.

**Comment by brianzelip** [comment]
@cdibella it hasn’t been merged into master since it’s not related to rep file version.

**Comment by brianzelip** [comment]
(So the Jira status was changed too early)

**Pull request merged**
