### PR TITLE
Remove skip_before_filter from controllers

### PR DESCRIPTION
**Pull request by cfitz**
This removes the skip_before_filter from the models, which was removed
in Rails a long time ago.. ( starting the app gives a depreciation warning )

Can't figure out why they want to skip verify_authenticity_token in the first place?

### CODE REVIEW

**Comment by pobocks** [comment]
So, this is just a guess, but are they skipping verification because these are forms that are generally public in some way, and are expected/allowed to be submitted to without starting from the application's forms?  They're all in the Public UI, and in controllers with search responsibilities.

@bobbi-SMR - am I guessin' right here?

**Comment by lmcglohon** [comment]
@bobbi-SMR @pobocks @cfitz Should we just replace 'skip_before_filter' with 'skip_before_action' like it says in the documentation?

**Comment by pobocks** [comment]
@lmcglohon I'd be 👍  on that.

**Comment by cfitz** [comment]
@lmcglohon @pobocks That seems ok, since the only non-GET form is the request form. I dont think rails checks the token on GET forms, just POST/PUT/DELETE.
But, it might be good to run this on the request form, especially since I think there's an XSS issue with that one?

**Comment by lmcglohon** [comment]
@cfitz @pobocks I am going to close this pull request and put in another one replacing 'skip_before_filter' with 'skip_before_action'

**Pull request closed without merging**
