### PR TITLE
Bulk Linking of Top Containers to Archival Objects

### PR DESCRIPTION
**Pull request by ives1227**
## Description
Allows users to link top containers to archival objects in bulk at the resource level using CSV or XLSX.  Linking can be by either an existing top container ID or by creating a new top container in the spreadsheet. To do this users:

1. Export a Top Container Template form 
2. Fill out the fields of the csv form.
    Some fields are prepopulated and should not be touched
    Minimum required user entered fields are: 
    a. Top Container Record Number (internal id) **XOR** (Top Container Indicator AND Top Container Type)
    b. Instance Type
   NOTE: Location ID and Container Profile ID can only link to new top containers.  Existing top containers will not be updated.
3. Use the ‘Link to Spreadsheet’ button on the resource edit screen, use the file selector to select the proper file, and click on ‘Link Top Containers’.
4. If all validations pass, it creates a background job to link the archival objects and the top containers.

This change was necessary because it allows users to link top containers in bulk instead of performing the mundane task of doing this one by one.

## How Has This Been Tested?
RSpec tests to test validation and uploading
Manual front end testing by developers and end users at Harvard.
The entire suite of tests was run to verify that the changes are not affecting other areas of code.

## Screenshots (if appropriate):
Download template link
DownloadContainerTemplate

Link to Top Container button added to the existing bulk import modal.  This modal appears when clicking on the "Link via Spreadsheet" when in edit mode at the resource level.
LinkTopContainerButton

Successful validation creates a background job.  Otherwise the modal will display errors
TopContainerJobCreated

When the background job is complete, the log displays what was created and linked.
Log

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mark-cooper** [comment]
@ives1227 thx for this contribution. The plan for this one is to first review: https://github.com/archivesspace/archivesspace/pull/1927 which updates the existing bulk import to work as a background job.

My understanding is you were in the loop on the development in that branch so hopefully things are relatively in sync, but it's possible some changes may be needed here depending on how #1927 shakes out.

**Comment by mark-cooper** [comment]
Hi @ives1227, #1927 has been reviewed and is undergoing user testing before it can be merged.

The working branch for this is actually here (not in #1927 directly):
https://github.com/archivesspace/archivesspace/tree/ANW-386-bulkimport

I took a look at your branch today and started by merging `ANW-386-bulkimport` into it.
Perhaps unsurprisingly there are conflicts. They don't look particularly overwhelming
as the foundations are relatively aligned. In most cases you have added methods that
look like they should be able to sit alongside the existing functionality just fine and
I don't see anything that looks like it would be fundamentally incompatible, although
there may be some wrangling around the validation support provided in ANW-386.

Is updating this branch to be up to date with ANW-386 something you will have time for?

**Comment by ives1227** [comment]
@mark-cooper - I will find time to do this.  Is there a preferred deadline for this?

**Comment by mark-cooper** [comment]
@ives1227 there is no deadline! But, in general, sooner is better and it would be ideal if you were able to update it by mid/late-September, which should allow time for review and testing so it can be included in the next release of aspace.

**Comment by mark-cooper** [comment]
@ives1227 just an FYI that the validation and conversion of bulk import to a background job has been accepted. Therefore you just need to sync up with the master branch for any updates to this one.

**Comment by ives1227** [comment]
@mark-cooper thank you.  I've been trying to get to this but have been delayed.  I'll merge from master soon.  What is the latest this can be completed to make it into the next release?

**Comment by ives1227** [comment]
@mark-cooper - I've merged the changes from master relating to the bulk import and refactored the necessary top container code.

**Comment by mark-cooper** [comment]
@ives1227 "What is the latest this can be completed to make it into the next release?" -- there is no date yet, so there should be another couple of weeks at least.

Thx, for updating the branch. GH is reporting conflicts, is that something you'll be able to look into?

**Comment by mark-cooper** [comment]
@ives1227 once again, thx for the updates. If you rebase with master you should have passing tests.

Just to update you on our side: we're aiming to have a release candidate soon for the next release of aspace in early November. We think this PR is big and complex enough that we can't review it sufficiently to include it in this upcoming release. However, we are planning on one more release this year in December, which will have only agents enhancement work plus this contribution (assuming that everything checks out).

**Comment by ives1227** [comment]
@mark-cooper and @lorawoodford - I rebased but the same frontend test is still failing.

**Comment by ktamaral** [comment]
Note: A replacement PR has been submitted #2147. This PR #1944 can be closed.

**Pull request closed without merging**
