### PR TITLE
AR-1371 #finish adding container_management update to be tracked in DB

### PR DESCRIPTION
**Pull request by cfitz**

### CODE REVIEW

**Comment by mark-cooper** [comment]
:+1: :zap:

**Comment by mark-cooper** [comment]
Although to be picky (and hopefully not annoying =) I'm not sure about the config setting ... I don't see much of a reason to include it really?

Perhaps make `already_run?` a class method and have the check in `main.rb` be `ContainerManagementMigration.already_run?`. The instance method `run` could still check `self.class.already_run?` for extra precaution. Does something along those lines sound reasonable?

I think avoiding a config setting that quickly becomes redundant after adding mandatory new functionality is cool if possible.

**Comment by cfitz** [comment]
Yeah, I agree that the config setting is pretty pointless, which I think @quoideneuf also suggested.

@bdwestbrook  do you think we can remove the setting entirely? The original PR ( https://github.com/archivesspace/archivesspace/pull/349 ) requested to set this to true, but it does seem pretty redundant ( unless we expect people to possibly want to not run the upgrade or run it again? )

**Comment by bdwestbrook** [comment]
I think many of us have come to agree that the only option not to use the new container mgmt. functionality is to stay with the current version and that there should be no need to run the container migration a second time, but, should one want to, one can be advised to keep  a backup of their current version and then to migrate that version again.

**Comment by cfitz** [comment]
@bdwestbrook  Got it. So we should remove the setting?
In addition, should we drop the container table? That is left behind ( which is what I think Maureen was asking about ).

**Pull request merged**
