### PR TITLE
Add Capybara + Selenium test to PUI

### PR DESCRIPTION
**Pull request by cfitz**
This adds Capybara/Selenium tests to the PUI.

The capybara test suite runs with the public:test task.
Tests can be added to the features directory. Included in one to test
for the back button issue that was causing the flash to incorrectly
display that there's a general error.

It is configured to allow for Firefox (default), Chrome, and Headless
Chrome. To use Headless chrome, set an environment variable of
SELENIUM_CHROME. To use regular chrome, set an environment variable of
SELENIUM_HEADY_CHROME.

### CODE REVIEW

**Comment by lmcglohon** [comment]
@cfitz Thanks for getting this started but the travis test is not passing. Looks like the issue is here: Capybara::ElementNotFound: Unable to find visible link "Collections" in spec/features/resources_spec.rb:17.

**Comment by cfitz** [comment]
@lmcglohon hm, ok it was complaining about the largetree asset not found, so looks like we needed to make sure the shared assets get copied over before running a test on a clean install. Let's see if Travis likes now... :crossed_fingers:

**Comment by cfitz** [comment]
FYI - It took me a minute to remember how to do this. Running ./build/run public:test runs the test suite, with the capybara tests included. export the SELENIUM_CHROME and SELENIUM_HEADY_CHROME env variables to use chrome/chromedriver.

**Comment by cfitz** [comment]
ja, that's addressed in #1244 . The Public PUI throws lots of exceptions that just get swallowed.

**Comment by alexduryee** [comment]
Cool - in that case, this all looks good.  I wasn't able to get the Firefox tests running locally, but Chrome (headless) went fine.

**Pull request merged**
