### PR TITLE
ANW-921 PUI citation tabs

### PR DESCRIPTION
**Pull request by brianzelip**
## Description

This PR updates the PUI citation modal by adding two tabs: one for citing the _item_, one for citing the _item description_.

PUI tabbed citation modal

## Related JIRA Ticket or GitHub Issue

[ANW-921](https://archivesspace.atlassian.net/browse/ANW-921)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by brianzelip** [comment]
@lorawoodford  - I figured out a hacky solution to create the data I wanted, which likely isn't the most efficient Ruby, see https://github.com/archivesspace/archivesspace/pull/1830/files#diff-2264a93a86835aa87211c74892cff68e

When we do nail down the model, I can update the views accordingly.

We'll also need to discuss what the protocol is for allowing user configuration of the default active citation tab as mentioned in the comments of [ANW-921](https://archivesspace.atlassian.net/browse/ANW-921)

**Comment by lorawoodford** [comment]
Hey @brianzelip - Tests are failing on this because citation information also needs to be updated in:

`public/app/models/archival_object.rb`
`public/app/models/digital_object.rb`

as those records also contain the citation button.  See, for example, http://462.lyrtech.org/repositories/2/archival_objects/2003

Also, parking here that there will likely be implications to the requests button functionality that will need to be addressed and some now-redundant code that should be removed.  I also want to investigate abstracting some of this out into a separate model so we can avoid so much code duplication.

Just wanted to acknowledge this as some work in progress and leave my preliminary findings here.  I'll talk to @cdibella shortly about defaults labels/language and the like and get back to you.

Thanks!

**Comment by brianzelip** [comment]
@lorawoodford see updated files for digital objects and archival objects.

I've only tested the fix on the digital objects view.

How do you create and view archival objects?

**Comment by lorawoodford** [comment]
@brianzelip - Archival objects are "children" of resource records.  So, in the staff side resource record, you click the "Add Child" button, ensure the child you add is published, and then it should populate on the public side (in a larger db this can take time as archival objects are on the latter end of the indexing process).  Happy to screen share with you if that doesn't make sense!

**Comment by brianzelip** [comment]
Thanks @lorawoodford, I've confirmed the archival objects citation works, and the tests pass.

**Comment by lorawoodford** [comment]
Heya @brianzelip - I haven't done a full code review of this yet, but I think it's at a state where it's ready to have a test server put up so that end users can test it out.  Any objection?

Additional commits can continue to be pushed and the test server should automatically update (though the builds take somewhere in the range of 30min to 2hr to complete).

**Comment by brianzelip** [comment]
Hey @lorawoodford,sounds good!

**Comment by lorawoodford** [comment]
Thanks for this first pass, @brianzelip .  I'll confirm when the test server is up!

**Comment by lorawoodford** [comment]
Don't want to forget to chat about this tomorrow @brianzelip so parking the test server here: http://anw921.lyrtech.org/public/

Unfortunately our test servers don't have the request functionality turned on by default, so we'll have to look at a local build to see what is going on there.  The other remaining questions are re: additional code cleanup/consolidation that might be possible/advisable, and setting the default tab as a config.  (Nothing new here, just wanting to summarize it all in one place.)

**Pull request merged**
