### PR TITLE
ANW-631 and ANW-700 add id prefixes to linker records

### PR DESCRIPTION
**Pull request by brianzelip**
## Description

This PR adds id prefixes to linker-rendered records in record edit views and Top Container search view in staff UI. Doing so provides greater context to staff about records that can often have the same display string but different ids.

screenshot of resource-record-showing-ids

screenshot of top-container-search-showing-ids

screenshot of hyphen separators in linker id prefix

## Related JIRA Ticket or GitHub Issue

- [ANW-631](https://archivesspace.atlassian.net/browse/ANW-631)
- [ANW-700](https://archivesspace.atlassian.net/browse/ANW-700)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by brianzelip** [comment]
@lorawoodford @cdibella What would you like the separator to be when there is more than one id part in the four part id? The screenshots above are currently showing a single white space character as separator.

**Comment by lorawoodford** [comment]
@brianzelip - Just re-kicked the tests and all appear to be passing. Let's add a single hyphen `-` as the separator, please.  At various different places both a hyphen and a period are used (hope to address that one of these days), but in this instance when you switch to the show/view versions of resource and accession record pages, the linked accession/linked resource tables both already use hyphens.  (See, for example, the linked resource here: http://test.archivesspace.org/staff/accessions/3)

Thanks!

**Comment by brianzelip** [comment]
@lorawoodford all set, see the newly added 3rd screenshot above for hyphen separator example.

**Comment by brianzelip** [comment]
@lorawoodford Noticed a bug so fixed it and refactored, and cleaned up debuggers.

**Pull request merged**
