### PR TITLE
Ar 994 mixed content rendered correctly

### PR DESCRIPTION
**Pull request by bobbi-SMR**
I created a new module **/public-new/app/controllers/concerns/manipulate_node.rb** that contains a method to process ead nodes embedded in text fragments (such as title).  Currently, it is only the title of the archival object that gets this treatment (mostly because I'm still lacking in understanding where other text fragments (such as those that compose the Abstract or Note) are found.  Once all the places where the text should be processed  are identified, the method can be invoked there, as well.

In order to support the rendering, I added more styles to the .scss

### CODE REVIEW

**Comment by mark-cooper** [comment]
You may have already considered this but did you take a look at the existing MixedContentParser? Any chance to crib from or augment?

https://github.com/archivesspace/archivesspace/blob/master/common/mixed_content_parser.rb

And tests? :wink:

**Comment by bobbi-SMR** [comment]
Hi, Mark!

I was out yesterday, so only saw this today.  One of the problems with joining a project 2/3rds of the way through is that I don’t always get to thoroughly review all the code that’s already there; I didn’t even know there was such a beast.

I’ll take a look at it today.

Thanks,
Bobbi

**Comment by cfitz** [comment]
Hi, 

The common/mixed_content_parser.rb uses the Jsoup library, which is pretty nice to work with.
However, to me this looks nice too since it's just using Nokogiri, which would allow you to dump the jsoup dependency. 

Dealing with EAD's "mixed content" is a fucking nightmare. It's used everywhere...all the different titles, all the different kinds of notes, names of agents...It's just horrible. 

Couple of  things to be aware of : 

Aspace [ has a feature to make wrapping text in <p> tag optional by allowing people to just create paragraph breaks with \n\n.  ](https://github.com/archivesspace/archivesspace/blob/master/common/mixed_content_parser.rb#L17) . So double linebreaks == EAD <p> tag. 

Also...when using Nokogiri::XML::DocumentFragment.to_xml , you'll need to specifically set the encoding, or things can get wonky: 
 irb(main):002:0> Nokogiri::XML.fragment("顯況入的於想例專活").to_xml
=> "\xE9\xA1\xAF\xE6\xB3\x81\xE5\x85\xA5\xE7\x9A\x84\xE6\x96\xBC\xE6\x83\xB3\xE4\xBE\x8B\xE5\xB0\x88\xE6\xB4\xBB"
irb(main):003:0> Nokogiri::XML.fragment("顯況入的於想例專活").to_xml(:encoding => 'utf-8' ) 
=> "顯況入的於想例專活"

**Comment by mark-cooper** [comment]
@bobbi-SMR I guess we can close this one, right? Future new public ui development goes here:

https://github.com/archivesspace/public-new

**Comment by bobbi-SMR** [comment]
Yup!

**Comment by cfitz** [comment]
Hi, 
One thing while it's still on my mind...you'll run into issues with namespace prefixes on that xlink stuff...

For example:
<ref xlink:href="foo">blah</ref>

That's the way it should be and that's they way people will tell you it...but that's rarely how it will be. The big reasons are that some versions of AT export this out as ns2:href and the archivesspace app itself doesn't add the xlink namespace on the "wrap & tag" feature. 

Nokogiri::XML('<ref xlink:href="foo">blah</ref>').root.keys
=> ["xlink:href"]

Ughh....maybe something like? 
Nokogiri::XML('<ref href="foo">blah</ref>').root.keys.any? { |k| k =~ /foo$/ } 

Also just remember there are some subtle differences running nokogiri on jruby ( since it's running pure java ).

**Comment by bobbi-SMR** [comment]
Yes, there’s a bug in nokogiri on jruby, which I’m trying to figure out a way to get around; at least with our repos that we’ve imported in a QA environment, sometimes Nokogiri *wants* the prefix to xlink, and sometimes won’t acknowledge it.

Cheers,
Bobbi

**Comment by cfitz** [comment]
yuck. yeah it's gotten better over the past 2 years, but there's still the odd thing that pops up...usually around namespaces and certain errors being raised. good luck.

**Pull request closed without merging**
