### PR TITLE
Add spreadsheet builder model and specs

### PR DESCRIPTION
**Pull request by stitching-coder**
## Description
Add spreadsheet builder model for bulk update

## How Has This Been Tested?
Testing with unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X]  My code follows the code style of this project.
- [X]  My change requires a change to the documentation.
- [X]  I have read the **CONTRIBUTING** document.
- [X]  I have authority to submit this code.
- [X]  I have added tests to cover my changes.
- [X]  All new and existing tests passed.

### CODE REVIEW

**Comment by stitching-coder** [comment]
@thimios I am continuing to work on unit tests.

**Comment by thimios** [comment]
@stitching-coder I have converted this to a draft PR. Go ahead and click "Ready for review" once you are done with specs and I will review asap.

**Review by thimios — APPROVED** [review]

**Comment by thimios** [comment]
@stitching-coder looks great, could you squash all commits into one and merge it?

**Comment by stitching-coder** [comment]
@thimios I do not have permissions to merge it.

**Pull request merged**
