### PR TITLE
Add a parameter to AdvancedSearchField so that plugins can define search fields as literal, allowing string fields to match

### PR DESCRIPTION
**Pull request by andrew-morrison**
## Description
I need to be able to add an advanced search field in the staff interface to search for records by the URLs they contain. To that end, I have written a plug-in that indexes those URL in a string-type Solr field (using the `*_u_sstr` dynamic field.) But, when I add a call to `AdvancedSearch.define_field` in the _search_definitions.rb_ file, it doesn't work. The reason is that queries sent to Solr have any colons converted to spaces, and URLs always contain at least one colon in the `://` part between the protocol and the hostname.

To fix it, this pull request adds a new optional parameter called `:always_literal`. If set to true then searches targetting the specified Solr field will have the "literal" flag set. That means the query sent to Solr retains any colons, and escapes them instead. If set to false, or omitted, it will have no effect.

## Related JIRA Ticket or GitHub Issue
None

## How Has This Been Tested?
The [attached](https://github.com/archivesspace/archivesspace/files/12784820/file_uri_search.zip) demo plug-in sets up a Solr index field called `file_uris_u_sstr` and adds it to the advanced search in the staff interface. It also add logging of the query string sent to Solr. This allows the following test procedure:

1. Create a digital object with a file version containing a file URI of `https://www.example.com/view?page=1`
2. Run an advanced search for the same URI.

It will match the digital object. The backend log contains this message:
```
QUERY STRING SENT TO SOLR: file_uris_u_sstr:("https\:\/\/www.example.com\/view\?page=1")
```
Without this change, it won't match the digital object, and the log will contain:
```
QUERY STRING SENT TO SOLR: file_uris_u_sstr:(https //www.example.com/view?page=1)
```
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by donaldjosephsmith — APPROVED** [review]

**Comment by donaldjosephsmith** [comment]
@andrew-morrison were you able to successfully run the public tests against this? I'm getting the same failures locally as the ones in CI. (Don't worry about the frontend failure)

**Comment by andrew-morrison** [comment]
I got inconsistent results when running the public tests locally, somehow getting more failures without the changes in this branch than with them. But there was a bug, due to my misinterpretation of the code I'd copied from `solr_field_for` to do the retrieval of field definitions. I've fixed that now, which seems to have resolved the public test issues, at least.

**Comment by thimios** [comment]
This does not have enough test coverage to be merged. @andrew-morrison if you could add some specs on this we could consider merging it.

**Comment by andrew-morrison** [comment]
I've added a test to verify that the correct query syntax is being sent to Solr with and without the new parameter.

@thimios: If this is sufficient, please can you re-open this pull request. I do not have the permissions to do so.

**Pull request closed without merging**
