### PR TITLE
Adds External Documents to Assessment

### PR DESCRIPTION
**Pull request by sephirothkod**
## Description
This adds External Documents to the Assessment Model. 

## Related JIRA Ticket or GitHub Issue
[ANW-1015](https://archivesspace.atlassian.net/browse/ANW-1015)

## How Has This Been Tested?
Spec has been added

## Types of changes
New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by mark-cooper** [comment]
@sephirothkod I just looked into why the tests are failing and the issue is:

```txt
     [java] Exiting
     [java] Web Console is activated in the test environment. This is
     [java] usually a mistake. To ensure it's only activated in development
     [java] mode, move it to the development group of your Gemfile:
     [java] 
     [java]     gem 'web-console', group: :development
```

Which is resolved by:

```diff
diff --git a/frontend/Gemfile b/frontend/Gemfile
index 1ba6f40fc..ae6e60a99 100644
--- a/frontend/Gemfile
+++ b/frontend/Gemfile
@@ -30,6 +30,10 @@ gem 'json-schema', '1.0.10'
 gem 'atomic', '= 1.0.1'
 gem 'jruby-jars', '= 9.2.12.0'

+group :development do
+  gem 'web-console'
+end
+
 group :test do
   gem 'rspec', '~> 3.6.0'
   # For performance testing
@@ -53,7 +57,6 @@ group :development, :test do
   gem 'pry-nav'
   gem 'pry-rails'
   gem 'rubocop', '~> 0.72.0', require: false
-  gem 'web-console'
 end

 gem 'mizuno', '0.6.11'
```

Are you able to update your pull requests? No worries if not, we can handle it ourselves, just wanted to ask you first.

**Comment by sephirothkod** [comment]
@mark-cooper I made the change in both branches, sorry for not seeing this earlier.

**Comment by sephirothkod** [comment]
Now this has failed on a test that hasn't been touched for this branch. Is this a test that periodically fails?

**Comment by mark-cooper** [comment]
Yes, unfortunately this one recurs from time to time only in GH:

```txt
     [java] Failures:
     [java] 
     [java]   1) Default Form Values will let an admin create default accession values
     [java]      Failure/Error: expect(@driver.find_element(css: '#accession_title_').text).to eq('DEFAULT TITLE')
     [java] 
     [java]        expected: "DEFAULT TITLE"
     [java]             got: ""
```

I've restarted it.

**Comment by mark-cooper** [comment]
@sephirothkod LGTM. Will be included in the next release. Thanks.

**Pull request merged**
