### PR TITLE
Adding ability to use Chrome in Selenium

### PR DESCRIPTION
**Pull request by cfitz**
This configures Selenium to use headless Chrome if an environment variable SELENIUM_CHROME is present. The Travis setup is changed to use Chrome rather than FF + XVFB 

Some changes to the selenium tests are also added to make them not fail so dang much for not gosh darn reason. These mainly have to do with the typeahead values, which seem to be the biggest culprits to the "random failures". 

Also adds "verbose" param for the indexer ( default is true ), which helps keep most of the indexer log output out of the test results output. 

Also fixes an error with the db:nuke in MySQL ( used by Travis ). 

Also updates the example MySQL jdbc url to add useSSL=false, since newer versions of jdbc give a warning when this is not set.

### CODE REVIEW

**Comment by cfitz** [comment]
I haven't been able to get Selenium + FF running on my laptop for Aspace for awhile. Chrome seems a little faster, and the headless version is nice. 

I was able to finally get this to pass "consistently", that is I ran the tests three times in a row with no failures on my laptop and [got Travis to pass it ](https://travis-ci.org/cfitz/archivesspace/jobs/285931974)
However, with travis you might still need to try and restart jobs that fail...

**Comment by cfitz** [comment]
Hm, looks like Travis came back with 3 errors. 

The first looks like a network issue pulling down gems, so suggest to  resubmit that
The last looks like a random out of memory error on the dist task, which I'd also suggest to resubmit, since it could have been a weird blip on the host

The second one I did see once on my laptop, but I don't think it has anything to do with the Chromedriver stuff. It looks like there's maybe a race condition or something that is causing XML exports to be slightly off? Not really sure...you could try and rerun the job and see what happens there...

**Comment by lmcglohon** [comment]
@cfitz Looks good!

**Comment by cfitz** [comment]
yeah! It passed!!!! 🍾 🍾

**Pull request merged**
