### PR TITLE
ANW-1206: visual cue for digitized materials (tree)

### PR DESCRIPTION
**Pull request by mark-cooper**
Addresses ANW-1206 Collection Organization tree linked digital object indicator.
This adds an icon to items in the tree that have associated digital objects.

This is only 1 part of the issue. The other will be addressed separately to make
implementation / review simpler.

## Related JIRA Ticket or GitHub Issue
https://archivesspace.atlassian.net/browse/ANW-1206

## How Has This Been Tested?
Manually & with specs.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by donaldjosephsmith** [comment]
This looks good in the header bar for the resource view, but ANW-1206 seems to indicate that there should be something displayed in the collection list, and at lower levels as well (series, etc). I'm not seeing anything in these other places. Is that being pushed off to the later issue?

**Comment by mark-cooper** [comment]
@donaldjosephsmith just to clarify: this PR is just for the right-hand "Collection organization" at the resource level in the PUI, the part containing the tree (not the "Collection Organization" tab).

For something to show up there needs to be a related digital object instance that is published. You will also need to reindex.

**Comment by donaldjosephsmith** [comment]
Ah, sorry, got it. Stand by

**Review by donaldjosephsmith — APPROVED** [review]
Ok, got it to show up now!

**Pull request merged**
