### PR TITLE
ANW-700 Add Related Accessions id to Resource edit mode

### PR DESCRIPTION
**Pull request by brianzelip**
## Description
This PR adds the Accession identifier to the "Related Accession" title string in the "Related Accession" section of the Edit Resource view.

The screenshots below show the id with

- [brackets] around them
- before a -
- and before a :

solution with id in brackets

solution with id before dash

solution with id before colon

## Related JIRA Ticket or GitHub Issue
[ANW-700](https://archivesspace.atlassian.net/browse/ANW-700)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by brianzelip** [comment]
While this solution works for the Resource Record Edit view, the Resource Record view now has a bug. Work in progress...

**Comment by brianzelip** [comment]
@lorawoodford All set now - I figured out a rails conditional and better string interpolation.

**Comment by brianzelip** [comment]
Hmmm, not sure why dcee2e3 broke the tests...

**Comment by lorawoodford** [comment]
Heya @brianzelip - I've added an inline comment about building out the full id and have tagged you in a related JIRA that may influence where/how the id is populated (since it should ideally appear in both the typeahead as well as the resulting blue linker text).  That said, this is a great first pass!

I consulted with @cdibella and the punctuation used should be your third option with a colon.

Finally, because of the conditional used in `application_helper`, I'm seeing extraneous empty [ ]s outside of the linked accessions area, such as:

image

Happy to talk through things if you'd like.  Generally speaking folks want these identifiers (which are concats of multiple stored id's) all over the place, so if we can find an extensible solution that would be ideal (I know, easier said that done).  

Also, I assume you saw that there was a prior attempt at resolving this issue (with inline comments about why it didn't work) here: https://github.com/archivesspace/archivesspace/tree/ANW-700

**Comment by brianzelip** [comment]
DOH!

**Comment by brianzelip** [comment]
@lorawoodford where is the inline comment that you referenced above

> I've added an inline comment about building out the full id and have tagged you in a related JIRA...

**Comment by brianzelip** [comment]
Closing this PR in favor of #1906

**Pull request closed without merging**
