### PR TITLE
append to log instead of overwrite

### PR DESCRIPTION
**Pull request by junkhacker**
changed logging from overwriting the log file on each startup to appending to the log if it exists. this preserves logging between service restarts and allows logrotate to copytruncate the log file without the program continuing to write from the previous offset, inadvertently creating large sparse files.

### CODE REVIEW

**Comment by Blake-** [comment]
Maybe a note in the docs rather than a full change to this? Seems like a major change.

https://github.com/archivesspace/tech-docs/pull/45

**Comment by junkhacker** [comment]
is there any reason to not make the change i suggested? I'll admit that i didn't do extensive testing (only Debian), but it seems like a straightforward and minor but important change to me. The current default setting prevents log rotation and doesn't preserve logs between service restarts. When you consider that the other default config settings cause the logging of a significant amount of data to the log file, the log file can grow quickly into the gigabytes without rotation. The docs should probably also mention the importance of setting up log rotation too.

**Comment by Blake-** [comment]
For sure! "The docs should probably also mention the importance of setting up log rotation too." that's a great idea! I'll be sure to do a PR for that.

I don't know about the `>` vs `>>` though. It's been `>` forever and a change like that means something major for all sites. I do understand your reasoning. I am not the one making the decision at all on this. I see the benefits for both ways, though in this case so much of how we run things depends on the `>` and I would guess others feel the same way. 

Also, it's an easy change for anyone who wants to append.

**Comment by junkhacker** [comment]
"I don't know about the > vs >> though. It's been > forever and a change like that means something major for all sites." this does make a valid point regarding existing practices. with my change, log files would continue to grow instead of clearing out when services are restarted, unless log rotation is set up. however, i still think that appending and setting up log rotation should become the default at some point.

i created a PR for the log rotation documentation, but what i wrote could probably be improved.

**Comment by Blake-** [comment]
I guess another option could be on start up check for .out and if it's there rename it and compress it to out.date.gz or something. No idea if that's something worth doing, but maybe worth looking into.

**Comment by lmcglohon** [comment]
This Pull Request will be closed because the solution should not be part of the core code but I believe the documentation included tech-docs is sufficient for someone implementing the solution locally.

**Pull request closed without merging**
