### PR TITLE
make sure not to accidentally set resource as a parent

### PR DESCRIPTION
**Pull request by quoideneuf**
Fix a bug that put the resource uri into the parent param when inserting before a top-level object

### CODE REVIEW

**Review by donaldjosephsmith — COMMENTED** [review]
I've verified that this fixes the problem. Should this if statement condition be inverted so that the empty block could be removed?

**Review by donaldjosephsmith — COMMENTED** [review]
I think that would need parens too?

**Comment by quoideneuf** [comment]
> I think that would need parens too?

I tested it again - it seems to do what is intended...

**Review by donaldjosephsmith — DISMISSED** [review]
That does work, but it's still a little confusing to me because you're doing a logical NOT on the "length" value and then comparing it to zero. What I had in mind for inverting the condition was flipping the > to a <= (or in this case == since it will never be less than zero). I may be being a little picky though 😆

**Comment by quoideneuf** [comment]
> That does work, but it's still a little confusing to me because you're doing a logical NOT on the "length" value and then comparing it to zero. What I had in mind for inverting the condition was flipping the > to a <= (or in this case == since it will never be less than zero). I may be being a little picky though 😆

Ok - I see. I changed to `length < ` - yes, more readable.

**Review by donaldjosephsmith — APPROVED** [review]

**Pull request merged**
