### PR TITLE
ANW-1020. uniq_ao_pos index constraint violation fix

### PR DESCRIPTION
**Pull request by dsteelma-umd**
## Description

When editing an archival object, a database constraint violation of the "uniq_ao_pos" index in the "archival_object" table may occur when saving the object, giving an error message similar to the following in the GUI:

```
translation missing: - translation missing: validation_errors.database_integrity_constraint_conflict_javacommysqljdbcexceptionsjdbc4mysqlintegrityconstraintviolationexceptionduplicate_entryroot@/repositories/2/resources/1608-500for_keyuniq_ao_pos
```

While the error message is superficially similar to that described in  AR-1326: DB Constraint Violation for transferred Archival Object positionsAccepted (https://archivesspace.atlassian.net/browse/AR-1326), the fundamental cause is different, as it occurs in ArchivesSpace v2.7.0.

As indicated in James Bullen's April 5, 2017 comment:

> In 2.0 we have refactored how positions are handled and resequencing is no longer required, so that config option has been disabled.

Due to the v2.0 refactoring, neither of the fixes mentioned in AR-1326 (i.e., resequencing on startup, or using the "https://github.com/archivesspace/resync" plugin) are relevant.

Upon investigation, the problem appears to be the following:

In the "backend/app/model/mixins/tree_nodes.rb" file, there is a distinction between "logical position" and "physical position" of an archival object. The "physical position" is the actual value in the "position" field in the "archival_object" table in the database. This value contains "gaps" to enable insertion of elements without having to change all the other elements to preserve the order of the object in the list. The "logical position" is the "gapless" position of the object in the list, used by the API.

When generating the JSON object from the database in the "sequel_to_jsonmodel" method, the "physical position" retrieved from the database is stored in the "json.position" field. This is replaced in the method by the "logical position", and the logical position is what is returned by the API. When the object is updated, the "json.position" field returned from the form still has the logical position. In the "update_from_json" method in "tree_nodes.rb", the object is saved to the database, where the JSON contains the logical position, not the physical position.

An example of this that we've seen occur is the following. In our database, the "physical position" of Archival Object #538301 is "501500", which has a "logical position" of "500". When attempting to save Archival Object #538301, the "json.position" field sent to update the database contains "500" (the logical positon), which conflicts with Archival Object #537801, which has a physical position of "500".

This problem only affects specific records because of the gaps in the physical position. As more records get added to the system, a logical/physical position conflict becomes more likely.

## Related JIRA Ticket or GitHub Issue

https://archivesspace.atlassian.net/browse/ANW-1020

## How Has This Been Tested?

Added test cases to the "backend/spec/tree_position_spec.rb" file that will
fail the logical position is used in writing the object to the database, and
which will fail if the physical position of an archival object changes after being
updated without having changed its logical position.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lmcglohon** [comment]
@dsteelma-umd thanks for this! We are currently in a code freeze because of a release candidate going out today. Once the release is out, a reviewer will be assigned so it will continue to move forward.

**Comment by mark-cooper** [comment]
Hi @dsteelma-umd 

I've just started to review this and it's looking good to me! I haven't actually run the branch or tests yet but in the interests of getting you some feedback sooner rather than later do you think the changes to `update_from_json` could be shortened to this?

```diff
--- a/backend/app/model/mixins/tree_nodes.rb
+++ b/backend/app/model/mixins/tree_nodes.rb
@@ -167,10 +167,8 @@ module TreeNodes
       # change the root record on the fly.  I guess we'll allow this...
       extra_values = extra_values.merge(self.class.determine_tree_position_for_new_node(json))
     else
-      if !json.position
-        # The incoming JSON had no position set.  Just keep what we already had.
-        extra_values['position'] = self.position
-      end
+      # ensure we retain the current (physcial) position when updating the record
+      extra_values['position'] = self.position
     end

     obj = super(json, extra_values, apply_nested_records)
```

I think this is doing the same thing as your changes but piggybacking on the existing `extra_values` hash to override `json.position` on update, then `json.position` can be used (having not been modified) to do the actual position updates as it is being done currently.

**Comment by dsteelma-umd** [comment]
Hi @mark-cooper ,

Thanks for your feedback. I don't believe the changes you suggest will work. I am assuming that you are suggesting keeping all my changes, except that the "update_from_json" method of the "backend/app/model/mixins" class should be modified to be:

```
  def update_from_json(json, extra_values = {}, apply_nested_records = true)
    root_uri = self.class.uri_for(self.class.root_record_type, self.root_record_id)

    do_position_override = json[self.class.root_record_type]['ref'] != root_uri || extra_values[:force_reposition]

    if do_position_override
      extra_values.delete(:force_reposition)
      json.position = nil
      # Through some inexplicable sequence of events, the update is allowed to
      # change the root record on the fly.  I guess we'll allow this...
      extra_values = extra_values.merge(self.class.determine_tree_position_for_new_node(json))
    else
      # ensure we retain the current (physcial) position when updating the record
      extra_values['position'] = self.position
    end

    obj = super(json, extra_values, apply_nested_records)

    self.class.ensure_consistent_tree(obj)

    trigger_index_of_child_nodes

    obj
  end
```

When I run the relevant unit test:

```
build/run backend:test -Dspec=tree_position_spec.rb
```
the change causes the following tests to fail:

* rspec ./spec/tree_position_spec.rb:77 # Tree positioning can swap two elements after some shuffling around
* rspec ./spec/tree_position_spec.rb:54 # Tree positioning can change the position of an object by updating it

**Comment by mark-cooper** [comment]
Yeah, that's right, keep your changes, only updating `update_from_json`, but I was suggesting:

```ruby
  def update_from_json(json, extra_values = {}, apply_nested_records = true)
    root_uri = self.class.uri_for(self.class.root_record_type, self.root_record_id)

    do_position_override = json[self.class.root_record_type]['ref'] != root_uri || extra_values[:force_reposition]

    if do_position_override
      extra_values.delete(:force_reposition)
      json.position = nil
      # Through some inexplicable sequence of events, the update is allowed to
      # change the root record on the fly.  I guess we'll allow this...
      extra_values = extra_values.merge(self.class.determine_tree_position_for_new_node(json))
    else
      # ensure we retain the current (physcial) position when updating the record
      extra_values['position'] = self.position
    end

    obj = super(json, extra_values, apply_nested_records)

    if json.position
      # Our incoming JSON wants to set the position.  That's fine
      set_position_in_list(json.position)
    end

    self.class.ensure_consistent_tree(obj)

    trigger_index_of_child_nodes

    obj
  end
```

**Comment by dsteelma-umd** [comment]
@mark-cooper,

I tried the suggested change, and the tests all pass. I've updated the pull request.

Thanks for you help,

David

**Comment by mark-cooper** [comment]
@dsteelma-umd excellent, thanks -- and also for providing such a thorough description of the issue and detail in the comments! 👍

**Pull request merged**
