### PR TITLE
Bump nokogiri to 1.8.4  & add test

### PR DESCRIPTION
**Pull request by cfitz**
This bumps the nokogiri version to 1.8.4 across all apps.

It also adds a test case for some character encoding in the ead3
serializer.

### CODE REVIEW

**Comment by cfitz** [comment]
https://github.com/archivesspace/archivesspace/pull/1321

**Comment by lmcglohon** [comment]
@cfitz It looks like you added nokogiri to Gemfiles (for indexer and public) that didn't have nokogiri previously. Can you explain the logic behind that?

**Comment by cfitz** [comment]
Yeah both indexer and public have gems that depend on nokogiri, but it
wasn't pinned in the Gemfile. This results in two versions of the gems
being in the build, which causes problems. I set the version in public and
indexer make sure it's using the same version as the others

**Comment by lmcglohon** [comment]
Fixes #1145

**Pull request merged**
