### PR TITLE
Ar 1646

### PR DESCRIPTION
**Pull request by marktriggs**
Incorporating suggestions from https://archivesspace.atlassian.net/browse/AR-1646

### CODE REVIEW

**Comment by lmcglohon** [comment]
@marktriggs Handle after 2.0.0 release

**Comment by jambun** [comment]
no 🇬🇼

**Comment by jambun** [comment]
🍪

**Comment by lmcglohon** [comment]
@jambun Can you put a comment in this explaining why you closed this without merging it? Thanks!

**Comment by jambun** [comment]
@lmcglohon we'll merge this into the new pui-dev branch - via a new PR

**Comment by jambun** [comment]
... in fact it's already happened ... https://github.com/archivesspace/archivesspace/pull/706

**Pull request closed without merging**
