### PR TITLE
Backend bulk updater gem, library, and tree mixin

### PR DESCRIPTION
**Pull request by stitching-coder**
Splitting up the bulk updater project into smaller pieces

Description
There is a method specifically for building a tree for the bulk updater and a spreadsheet builder model
https://github.com/hudmol/as_spreadsheet_bulk_updater

How Has This Been Tested?
Tests added for the new method and model

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have authority to submit this code.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by stitching-coder** [comment]
@thimios I have broken the bulk updater down into smaller pieces. I believe this is ready to add.

**Review by thimios — CHANGES_REQUESTED** [review]
@stitching-coder Do we have to include the xslt-streaming-reader gem in our lib file? I was trying to locate this gem on github but could not. If it is not published, would it be possible to actually publish it?

The rest looks good to me.

@stitching-coder could you also rebase it on the latest master? I think this is why the CI jobs are not running properly.

**Comment by stitching-coder** [comment]
@thimios xslt-streaming-reader is owned by Hudson Molonglo who decided not to publish it. I thought about adding to the Gemfile pointing to the GitHub repo but was concerned it might disappear.

**Comment by stitching-coder** [comment]
I'll try to rebase to the latest master.

**Comment by thimios** [comment]
> @thimios xslt-streaming-reader is owned by Hudson Molonglo who decided not to publish it. I thought about adding to the Gemfile pointing to the GitHub repo but was concerned it might disappear.

@stitching-coder in that case I would rather clone it in our organization and keep it in a separate (essentially public) repository than including it in this repository. In any case, including it here would essentially publish it. I can contact Hudson Molonglo and ask them if they are fine with keeping it in a separate repository within the archivesspace organization. I think keeping a gem within this repository looks very ugly and would prefer to avoid it. What do you think?

**Comment by stitching-coder** [comment]
@thimios I think adding it to the archivesspace org is a great idea!

**Comment by stitching-coder** [comment]
@thimios I have removed the xlsx_streaming_reader and am pointing to the GitHub repo until the repo has been cloned or forked into the archivesspace org.

**Review by thimios — APPROVED** [review]

**Pull request merged**
