### PR TITLE
Lcnaf mods : fix LOC lsch import, add lcsh (subject) import. 

### PR DESCRIPTION
**Pull request by sdm7g**
* The 'loc' import option was not actually importing from LOC, it was using SRUsearcher methods on import. That is now fixed.
* Added lcsh subject import. 

To Do:
* add more tests 
* assign authority-id's on import. 
( I'm still working on these, but I wanted to give you a head's up on the current fixes. )

### CODE REVIEW

**Comment by quoideneuf** [comment]
Looks good, but I found  a few minor formal issues with this PR. 

1. There's a bunch of merge commits. Can the branch be rebased or can these be squashed? Let me know if you want instructions for doing this.

2. Forgot a javascript debugging message here: https://github.com/uvalib/archivesspace/blob/lcnaf-mods/plugins/lcnaf/frontend/assets/lcnaf.js#L10

3. I also noticed a few lines with 4 space indents rather than 2 spacers.

**Comment by sdm7g** [comment]
> On Sep 14, 2015, at 10:01 PM, Brian Hoffman <notifications@github.com> wrote:
> 
> Looks good, but I found a few minor formal issues with this PR.
> 
> There's a bunch of merge commits. Can the branch be rebased or can these be squashed? Let me know if you want instructions for doing this.
> 
> 

Yes. How do I squash or rebase ? 


> Forgot a javascript debugging message here: https://github.com/uvalib/archivesspace/blob/lcnaf-mods/plugins/lcnaf/frontend/assets/lcnaf.js#L10 <https://github.com/uvalib/archivesspace/blob/lcnaf-mods/plugins/lcnaf/frontend/assets/lcnaf.js#L10>
> I also noticed a few lines with 4 space indents rather than 2 spacers.
> 
> 
> 
Thanks. I’ll fix these and finish my other fixes.  

— Steve.

**Comment by quoideneuf** [comment]
@sdm7g - Well, it looks like you have been updating your fork using merge commits from origin/master. It's generally better to just use reset --hard to zap your fork's master branch and get it back inline with origin/master. You can do that now, something like:

    git pull origin master
    git checkout uvalib master
    git reset --hard origin/master

Assuming there is no original work in uvalib/master, this should be fine, and will sync your fork to the origin.

Once that is done, you want to replay your feature branch's commits onto the updated master:

    git rebase master

You're probably going to see two conflicts, which you'll need to resolve:

    git rm selenium/spec/selenium_spec.rb

And you'll need to edit this file and remove the lines marked "HEAD" in favor of the lines in the upstream origin:
backend/app/model/reports/jasper_report.rb. It's important that you choose the right edits here, so you don't undo changes in the origin codebase.

Then you'll need to add that file and continue the rebase:

    git add backend/app/model/reports/jasper_report.rb
    git rebase --continue

Once that completes, you should see a cleaned up log with only your substantial commits.

**Comment by sdm7g** [comment]
OK: did the rebase as above, but did not see any conflicts reported. 
Made those minor edits and pushed branch lcnaf-mods. 
Do I have to issue another pull request? 

I found a bug: when selecting more than one name or subject in LCNAF/LCSH, it's only importing the first.  I need to strip off all of the `<?xml ` declaration lines and put back the `<collection>` wrapper.

**Comment by quoideneuf** [comment]
You will have to create a new pull request, and since you are "rewriting history" you'll need to either delete your remote feature branch and rewrite it, or just push to a new remote feature branch.

   git push uvalib :lcnaf-mods
   git push ovalib lcnaf-mods

Note that I'm assuming you are the only person working on this branch. It is a bad idea to delete remote branches if other people are using them

**Pull request closed without merging**
