### PR TITLE
Allow to break out backend,staff,public, indexer into their own logs

### PR DESCRIPTION
**Pull request by cfitz**
This allows for apps to be broken out into their own logs, as well as
ability to set the log levels. By default, all logs will still output to
$stderr. This can be changed to a file on a per app basis.

The "logging.rb" was pulled out of the backend and put into common ( as "log.rb" ) in order to make the indexer behave the same as the backend ( since they're both Sinatra apps ). 
Rails apps ( frontend and pui ) were tweaked to act the same as well

### CODE REVIEW

**Comment by lmcglohon** [comment]
@cfitz This looks great - very excited to put this in! Can you rebase this to the current master? I have updated versions of some of the gemfiles past the versions you have. As soon as that happens, I will get it put right in for the next release.

**Comment by cfitz** [comment]
@lmcglohon no problem. let me know if this works....

**Comment by cfitz** [comment]
@lmcglohon should we remove the "log monitoring" bit? I think it's pretty janky, not sure it's really useful,  and we could replace it with something a little better.

**Comment by cfitz** [comment]
@lmcglohon  Also...kind of think this would be better to do in Jetty, especially when we upgrade to jetty 9. We could add some bits to have Aspace do its own log rotation as well, which is a big pain point for a lot of folks  (especially windows ).

Also...i think jetty 9 is easier to configure to run SSL and bind to privileged ports, so we could make it so people can run on 80 or 443.

**Pull request merged**
