### PR TITLE
ANW-170, ANW-490: Make datepickers opt-in

### PR DESCRIPTION
**Pull request by brianzelip**
## Description

This PR closes [ANW-170](https://archivesspace.atlassian.net/browse/ANW-170) and [ANW-490](https://archivesspace.atlassian.net/browse/ANW-490) by making the datepicker opt-in by leveraging the calendar icon to the right of each date input as a datepicker toggle switch.

ANW-170 ANW-490 opt-in to datepicker

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by brianzelip** [comment]
@quoideneuf this is still a WIP, but the latest commit addresses both ANW-170 and [ANW-490](https://archivesspace.atlassian.net/browse/ANW-490) by making the calendar icon to the right of the date input a toggle switch for the datepicker.

**Comment by brianzelip** [comment]
@quoideneuf The breaking tests pointed out there is some funny business going on in the advanced search regarding applying the `has-error` class to the date input - the code in frontend/app/assets/javascripts/header.js is not playing well with the new changes in frontend/app/assets/javascripts/utils.js yet. I'm still looking into it as well as the breaking tests.

**Comment by brianzelip** [comment]
We'll see what the rest of the tests do now after recent changes. Now that the date picker is toggle-able, I'll write some tests for that.

**Comment by brianzelip** [comment]
@quoideneuf Ok this is ready for review now.

**Review by quoideneuf — DISMISSED** [review]

**Comment by quoideneuf** [comment]
I had to rebase this due to an unrelated translations file conflict.

**Review by quoideneuf — APPROVED** [review]

**Pull request merged**
