### PR TITLE
AR-1329 #finish adding on_delete => cascade to certain record types t…

### PR DESCRIPTION
**Pull request by cfitz**
…o help with repo deletion

### CODE REVIEW

**Comment by cfitz** [comment]
@quoideneuf  what do you think? a little worried about the FK changes, but also think they help..

**Comment by mark-cooper** [comment]
:bow: 

Just had a couple of reports re: this issue recently, from a couple of sources.

**Comment by cfitz** [comment]
@mark-cooper yeah, i bet some of the sources where the same...so are the reports about deleting repos? not something related to the FK changes in this PR? 

sorry..being a bit paranoid about these, i think.just dont want something that horks the DB

**Comment by quoideneuf** [comment]
@cfitz - I'm no MySQL expert, but the cascades don't look dangerous to me. I do wonder if deleting jobs with their owners will ever have unwanted repercussions...but probably not. 

Also, this might be a separate issue, but I noticed that deleting the repo does not delete the agent_corporate_entity for the repo. This means you can't name a repo after an old deleted repo.

**Comment by quoideneuf** [comment]
Also probably a separate issue - is it supposed to be possible to delete a repo while it still has accession records? Because it does appear to be possible, the accessions (and their events) get quietly deleted.

**Comment by mark-cooper** [comment]
@cfitz yeah, reports were just about being unable to delete repos.

**Comment by cfitz** [comment]
@mark-cooper  yes, i got a report about this 2 days ago...from a hostee i think

@quoideneuf  yeah, I'm not sure...do we want to re-owner the jobs? But, yeah I assume the corp_entity needs to get removed...but crap if it's linked to records in other repos?!? ack!!!! :hankey:

**Comment by cfitz** [comment]
I'm thinking we can take this now and come back to the agent_corp_ent. issue...right now there's people who can't delete repos if they have import jobs, which is a PIA. This fixes that...

**Pull request merged**
