### PR TITLE
Docker: Added Database wait, MYSQL vars, and volume mounts for config and data

### LINKED ISSUE #1456: Docker startup can cause ArchivesSpace to run in a failure state indefinitely
If you run a `docker-compose up` or a `docker stack deploy` for a stack that contains an ArchivesSpace service along with a MySQL Service, where

1. ArchivesSpace is not built from source,
2. ArchivesSpace does not have a deploy package, and 
3. ArchivesSpace does not have any plugins to initialize,

then the ArchivesSpace service typically gets to the `setup-database.sh` script before the MySQL service is ready to accept connections. This causes the database setup script to fail, but the failure does not cause the container to exit. Instead, the docker-startup.sh will move on to running `archivesspace.sh`, which will continuously fail forever, until the service or container is either restarted, or the mysql database is set up manually.

## Expected Behavior

It seems that Docker services typically exit whenever there is a failure in the Docker container prior to the execution of the app itself, sometimes including failures with the app itself. If the container fails in this way, it allows the Docker daemon to determine if the service needs to be restarted, depending on the service's configured restart policy. This allows you to rely on Docker a little bit when designing Docker startup scripts. Automatic service restarts are turned on by default for Docker stacks, and can be enabled for docker-compose stacks.

docker-compose: https://docs.docker.com/compose/compose-file/#restart
docker stack: https://docs.docker.com/compose/compose-file/#restart_policy

## Current Behavior

If `/archivesspace/scripts/setup-database.sh` is reached before the mysql service is ready to accept connections, then the database will never be set up or migrated. This means you have to perform some sort of manual step when starting ArchivesSpace using the default `docker-startup.sh`.

1. Start the `db` service first, then wait for a bit, then start the `archivesspace` service.
2. Watch the logs of the `db` service, then restart the `archivesspace` service once the `db` service is ready for connections.

## Possible Solution

I'm putting in a pull request to add in a hard failure for db connection issues when running the db setup script, which I will link shortly. This PR adds an exit status check after the database setup script, which will echo and then exit if the database setup fails, identical to what's currently happening if `wget`ing the `ASPACE_DEPLOY_PKG_URL` fails.

An alternative to this would be to add a `set -e` to the top of the Docker startup script, which would be a little more invasive change and would prevent the startup script from being able to echo a message to the logs when a failure is detected.

## Steps to Reproduce

This happens for both `docker-compose` workflows, as well as `docker stack deploy` workflows.

```yml
version: '3.2'
services:
  db:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2 --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: archivesspace
      MYSQL_USER: as
      MYSQL_PASSWORD: as123

  archivesspace:
    image: archivesspace/archivesspace:2.5.2
    environment:
      APPCONFIG_DB_URL: "jdbc:mysql://db:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123"      
    depends_on:
      - db
```

## Context

I'm starting to spin up production instances of ArchivesSpace as Docker containers, as part of an automated deployment pipeline. I also spin up new local instances of ArchivesSpace for testing and migration purposes, sometimes multiple times a day. It would be nice if I could just `docker-compose up -d` or `docker stack deploy` and walk away for a while, without having to worry about ArchivesSpace getting stuck or requiring manual attention.

I have been using some workarounds to address for a while, but I figured it might be time to put in an issue and a pull request.

## Environment

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

### LINKED ISSUE #1495: Unclear documentation on Docker Container
I am trying to setup Archives Space via docker for production use but there seems to be a lack of documentation for it. 

When I pull down the docker container from [Dockerhub](https://hub.docker.com/r/archivesspace/archivesspace) there is no information on environment variables I need to set. As it currently stands, if i run the docker container Archives Spaces tells me what I am running the demo database and it should not be used in production. 

From digging around in this repo I see that you have a docker compose file, which is helpful, but no where in the documentation does it mention this. Additionally, none if the environment variables are documented in there, so I have very little to go off of. 

Right now, I am testing out my docker compose file with just `APPCONFIG_DB_URL` set, but I would love to know what the other environment variables are and what they do. It seems that to just get Archives Space up and running I need the DB URL.

Is there a plan moving forward to document this setup and if so can I contribute? 

Here is my docker file for reference: 

```
  database:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: archivesspace
      MYSQL_USER: as
      MYSQL_PASSWORD: as123
    restart: always
    volumes:
      - /volume1/docker/mysql-archivesspace:/var/lib/mysql
  archivesspace:
    image: archivesspace/archivesspace:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8089:8089"
      - "8090:8090"
    depends_on:
      - database
    environment:
      APPCONFIG_DB_URL: 'jdbc:mysql://database:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123'
      # disable the embedded solr
      # testing plugin initialization on startup
      #ASPACE_INITIALIZE_PLUGINS: 'newrelic'
    links:
      - database

```

### PR DESCRIPTION
**Pull request by Dr-Crow**
## Description
Added support for a database wait function. This stops docker containers from entering a restart loop. 

Added MYSQL vars to allow for a more docker experience.

Added support for volume mounts of data and config folders 

Most of the code came from @AustinTSchaffer, he was a big help in all of this!

## Related JIRA Ticket or GitHub Issue
Fixes #1456 
Kind of Fixes #1495

## Motivation and Context
Most of the context to these issues stem from #1456 

## How Has This Been Tested?
Here is my docker-compose file:
```
version: '3'
services:
  database:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /volume1/docker/Archivesspace/mysql-archivesspace:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2
    env_file:
      - database.env
  archivesspace:
    image: archivesspace/archivesspace:latest
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8089:8089"
      - "8090:8090"
    volumes:
      - /volume1/docker/Archivesspace/data-archivesspace:/archivesspace/data
      - /volume1/docker/Archivesspace/config-archivesspace:/archivesspace/config
      - /volume1/docker/Archivesspace/plugins-archivesspace:/archivesspace/plugins
    environment:
      DB_ADDR: database
      MYSQL_PORT: 3306
    env_file:
      - database.env
    depends_on:
      - database

```

This test the volume mounts and database wait. You can see the database wait in the logs.
To do a little more testing add a `APPCONFIG_DB_URL` to the above config. It should exit the startup script with an error, saying you can't have both `APPCONFIG_DB_URL` set and MYSQL vars. 

## Screenshots (if appropriate):
N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by AustinTSchaffer** [comment]
@Dr-Crow, I would like to not be associated with this pull request.

I have not used a docker startup script like this in over a year, preferring container shutdown over any built-in "wait for DB" functionality.

**Comment by Dr-Crow** [comment]
@AustinTSchaffer No problem. I just wanted to give you credit, since I used your snip it of code as a base. 

Are you still using the MYSQL_XXX variables?

**Comment by AustinTSchaffer** [comment]
@Dr-Crow, no, I just use the `APPCONFIG_DB_URL` setting, plus a few settings for allowing the container to work with my autoreverseproxy service. I typically the default db credentials (`as`/`as123`) anyway, since I'm mostly running the containers locally or in already restricted environments.

**Comment by mark-cooper** [comment]
@Dr-Crow thanks for taking the time to make a pull request, that's always appreciated. My feeling here is that we're adding complexity to the startup script without meaningfully improving upon the status quo.

"Edit: I rely on the container shutdown/autorestart functionality when spinning up instances that use a MySQL DB service." -- is what we do also, and makes the custom MySQL startup checks unnecessary.

**Comment by lmcglohon** [comment]
@mark-cooper Not sure what your final decision was on this PR - accept/merge, needs more impelmentation, reject?

**Comment by Dr-Crow** [comment]
@mark-cooper I love what you guys are doing with ArchivesSpace, but I am getting conflicting view points from you guys. 

You stated that Docker is an unsupported install method, but then state you are happy to get community contributions towards making the Docker functionality better. That’s what I am trying to do here, with adding the wait/delay for the Docker database container. 

You also seem to be against dividing user base from traditional installs verse docker installs. Hence, why I tried to add it in the docker start up script, thus not dividing the code base. A better potential place for this fix would be adding the database wait/delay functionality into the code instead of putting it the docker start up script. 

I personally think that have a docker container get stuck in a crash boot loop is not a solution to this problem. There should be a more graceful way of fixing this error. 

I am just not sure how to do that with the restrictions you placed around the docker portion of this project. I think having Docker as an install method is an amazing idea; even if it’s an unofficial install method. It enables people in the archival world who are less techy to utilize ArchivesSpace. 

But I worry that even if I propose changes, they are just going to be reject, thus wasting my time and yours. I am willing to work with you guys on supporting docker, but want to know where you guys stand on the topic. 

I am fine with closing this PR, if we can implement some sort of fix somewhere else in the code that you would be okay with.

**Comment by mark-cooper** [comment]
"You stated that Docker is an unsupported install method, but then state you are happy to get community contributions towards making the Docker functionality better."

Docker is unsupported as an install method. Docker "officially" is being used for internal purposes only. Use of Docker by anyone else is "use at your own risk". Docker related files may be updated at anytime with no advanced warning or presence in release notes. 

I'll add this text as a comment to the docker related files to make this clear.

Generally speaking I'm not sure I agree that we have a mixed message. ArchivesSpace is an open source project so we want to welcome and encourage contributions from anyone. If someone wants to use Docker and presents a way of improving the existing Docker functionality in a pull request it would (and has) been accepted. However if the maintainers feel the pull request does not meaningfully improve on the status quo then it will be rejected. This is obviously a subjective call, so we try to be as accommodating as possible.

"A better potential place for this fix would be adding the database wait/delay functionality into the code instead of putting it the docker start up script"

In that case you can create a Github or Jira issue and try to get support for your idea.

**Pull request closed without merging**
