### PR TITLE
Hm qsa 091520 mc

### PR DESCRIPTION
**Pull request by mark-cooper**
Includes two commits from the larger #1896 funded by Queensland State Archives and written by:

- @jambun
- @payten

## Commits

- 52c17d1c27e41affd75e76019adba62011d85b40: Only render View Published toolbar action if AppConfig[:show_view_published]
- 9078049affaf29a10331369570dc201c6d7a38d0: Add the ability to download a CSV of all enumerations with their values

There are a couple of small updates applied to the above commits:

- Use existing appconfig setting to determine visibility of view published (rather than a new one)
- Added position and readonly columns to enumeration csv export
- Exported csv filename does not include spaces

## How Has This Been Tested?
Manually, and test added for csv export endpoint.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lorawoodford** [comment]
@mark-cooper #1825 added the "View Published" toolbar button to aos/docs in `frontend/app/views/shared/_component_toolbar.html.erb`.  Can we add the AppConfig check in that location as well for consistencies sake?

**Review by lorawoodford — APPROVED** [review]

**Comment by jdshaw** [comment]
Works as expected.  Built a local dev instance and then toggled [:enable_public] config entry.  Visibility of the 'view published' button determined by true or false for [:enable_public].

**Comment by ebeckman87** [comment]
The CSV exporter works as expected.  Downloaded archival_record_level = collection search results using the "Download CSV" button.

**Comment by jlecampbell** [comment]
CSV export of enumerations works as expected.

**Pull request merged**
