### PR TITLE
ANW-1112 Restrict merge if denied contact details

### PR DESCRIPTION
**Pull request by mark-cooper**

### CODE REVIEW

**Comment by mark-cooper** [comment]
Rubocop reformatting makes this look like a lot more than there really is. It's somewhat better with: `git diff -w ANW-429...ANW-429-agent-contact-deets-merge`

The real change is here: https://github.com/archivesspace/archivesspace/blob/1e0f302ec85cc10dec6eb33a4ec91455ceae219a/frontend/app/controllers/agents_controller.rb#L217-L248

**Comment by lorawoodford** [comment]
Once I figured out the right combo of permissions to get this showing, worked fine for me.  Just wanted to ping @cdibella for feedback on the warning text, but otherwise this looks gtg.

image

**Comment by cdibella** [comment]
Let's change the text to:

The merge cannot be completed because one or more of the agents has contact details you do not have permission to access.

**Comment by mark-cooper** [comment]
@lorawoodford language has been updated 👍

**Review by lorawoodford — APPROVED** [review]

**Pull request merged**
