### PR TITLE
ANW-354 Remove bulk and inclusive date types from event records

### PR DESCRIPTION
**Pull request by lorawoodford**
Note that this involves db migration 098, and so does #1141 .  Since I don't know whether both or none or one PR will be accepted and, if both accepted, in what order, I've left them both 098, but whichever PR gets accepted second will need to be modified making the db migration 099.

### CODE REVIEW

**Comment by lmcglohon** [comment]
@pobocks @mark-cooper Do you think this is ready to merge? If so, please go ahead and merge it. If not, can you add your comments?

**Comment by mark-cooper** [comment]
@lmcglohon I haven't had a chance to run it yet, but from an overview perspective it looks fine.

@lorawoodford for the migration when dealing with explicit, single values (like `.select(:id)`) I prefer `.get(:id)` as it returns the value, not a dataset, which can sometimes not work as expected depending on the circumstances. But if there's already a precedent for an update done this way then it should be fine.

https://sequel.jeremyevans.net/rdoc/classes/Sequel/Dataset.html#method-i-get

**Comment by lorawoodford** [comment]
@lmcglohon @mark-cooper No, I'd still like to try and refactor the db migration per a conversation I had with Mark, but just haven't had the chance yet.  My preference would be to put this off until the next release since I'm fairly preoccupied this week.

**Comment by lorawoodford** [comment]
Ok, I changed those .select's to .get's and it still seems to be working as intended.  I also addressed the fact that I had forgotten to update `es.yml` and `fr.yml` in the first PR.  This is ready for review again @mark-cooper @lmcglohon

**Comment by lmcglohon** [comment]
@mark-cooper This looks good to me.  Can you review once more and merge if you are OK with it?

**Comment by mark-cooper** [comment]
@lorawoodford In the migration the `enum` id isn't used. Also, I think it's probably 95%+ safe as is but wrapping the gets with a truthy check might be a prudent idea. Weird things happen in the wild:

```rb
  up do
    range = self[:enumeration_value].filter(:value => 'range').get(:id)
    bulk_date = self[:enumeration_value].filter(:value => "bulk").get(:id)
    inclusive_date = self[:enumeration_value].filter(:value => "inclusive").get(:id)

    # changing all event dates that are bulk dates to ranges
    if bulk_date and range
      self[:date].exclude(:event_id => nil).filter(:date_type_id => bulk_date).update(:date_type_id => range)
    end

    # changing all event dates that are inclusive dates to ranges
    if inclusive_date and range
      self[:date].exclude(:event_id => nil).filter(:date_type_id => inclusive_date).update(:date_type_id => range)
    end
  end
```

**Comment by mark-cooper** [comment]
Tried out the UI part. Works fine for me 👍 so just ^ to consider.

**Pull request merged**
