### PR TITLE
ANW-1522 first pass at representative file versions for all record types

### PR DESCRIPTION
**Pull request by quoideneuf**
Tests for remaining representative file version data model changes, and a rough implementation that will need refactoring: either (or both) more targeted queries or make the `representative_file_version` and opt-in at the controller level, so that only the indexer gets it (as it really just needs to get to Solr so it can be displayed in the PUI.)

I am posting this as-is so we can move forward with the views for Resources, Accessions, and Archival Objects.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by brianzelip — COMMENTED** [review]
- Don't we still need [`representative_file_version`](https://github.com/archivesspace/archivesspace/pull/2670/files#diff-6725681e1f9e33791a5ae1d77b43c357c4d86c0e56831c9e2e48505f30cb5995L22) in the digital_object schema since it's computed in the [mixin](https://github.com/archivesspace/archivesspace/pull/2670/files#diff-bef6239f83c81586c3f4d48eb60a2d9dbc3e4efe5aee1f5a749b51e5a0eec72fR43)?
  - if so then should the same property also be added to the [digital_object_component schema](common/schemas/digital_object_component.rb#L18)?

**Review by brianzelip — COMMENTED** [review]
- minor followup in adapting variable names copy/pasted code from digital_object spec to [digital_object_component spec](https://github.com/archivesspace/archivesspace/pull/2670/files#diff-e9c8c3224525d15aafbf5ab3fa85a8f5427f7235b02aa9c8fd9845ca7c9f810fR87)

**Review by brianzelip — APPROVED** [review]
Looks good and makes sense.

**Comment by quoideneuf** [comment]
> Don't we still need [`representative_file_version`](https://github.com/archivesspace/archivesspace/pull/2670/files#diff-6725681e1f9e33791a5ae1d77b43c357c4d86c0e56831c9e2e48505f30cb5995L22) in the digital_object schema since it's computed in the [mixin](https://github.com/archivesspace/archivesspace/pull/2670/files#diff-bef6239f83c81586c3f4d48eb60a2d9dbc3e4efe5aee1f5a749b51e5a0eec72fR43)?
> * if so then should the same property also be added to the [digital_object_component schema](common/schemas/digital_object_component.rb#L18)?

Making use of `"parent" => "abstract_archival_object"` to avoid duplication.

**Pull request merged**
