### PR TITLE
Add docker dev files

### PR DESCRIPTION
**Pull request by mark-cooper**
This is backwards compatible with how things are currently.

Quick-start for testing would be:

```bash
docker-compose -f docker-compose-dev.yml build
docker-compose -f docker-compose-dev.yml up --detach
source .env.dev
# now run commands as normal with MySQL and external Solr
```

When using docker with the env file variables there is separate db and solr for dev (3306/8983) vs. test (3307/8984).

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mark-cooper** [comment]
@quoideneuf @lorawoodford double assigned because I'm sure we all want to agree on this one =)

This PR should maintain the status quo (not exactly but effectively), so Derby, embedded Solr is the default, and Github Actions is unchanged (MySQL with embedded Solr).

I had issues with the MySQL client gem, but using the connector .jar is fine (download to common/lib). We may want to add downloading the connector to bootstrap (but exclude it from the release pkg 'cus license).

The env file is a stopgap to make it easy to "switch" to using MySQL and external Solr for dev / test. However it's not guaranteeing that everything works with external Solr (I think some tests fail), which is fine for now.

If we're all happy with this and merge it next phase is to identify the Solr version to use, fix up any failing tests (so all should work across the board -- Derby, MySQL, embedded & external Solr), and enable external Solr with Github Actions (so it's MySQL and external Solr there).

After that: review external Solr config, make it the default for development / test, start to remove embedded (etc.) -- TBC

**Comment by quoideneuf** [comment]
Hi @mark-cooper  - nice! it is exciting to see this. I have a couple of comments, take them with a grain of salt as I have only looked thing over and not actually run anything.

1. Is it possible to keep things simpler in the build.xml by using separate 'dev' and 'test' env files rather than parallel tasks and variables?
2. Likewise with the docker containers - would it work to just have a single db and Solr service, then use environment to set the db name / collection name? (Though maybe there is a case for separate containers just to make it less likely to interfere.)
3. For the task that resets Solr to support scenarios where the Solr schema changes between test runs, I think it will require that the Solr collection and config actually be destroyed and re-posted. I have scripted that process before, so let me know if you want to delegate that part to me.
4. What do we mean by "release" in the release docker? 
5. Minor point, but it looks like some MRI gems are getting into the top-level Gemfile. Is that intentional? Do we want to keep to jruby for anything in the repo?

**Comment by mark-cooper** [comment]
1. There are other ways to do, but it gets complicated, either needing to parameterize the tasks or push the variable resolution into code (as it is was, inconsistently, before). I think on balance, having tried out a bunch of things, separate tasks achieves having separate dev & test environments unobtrusively (to the developer), and with the most convenience and simplicity.
2. We could certainly use a single db and solr container, rather than multiple, as the default. Right now it's easier to do it with multiple containers by default (because of the how the images are constructed) and I wanted the first PR to do only what is necessary to take a step forward with the fewest possible changes. So maybe we can evaluate what we want the default to be for the next PR?
3. Yeah, I'm happy to have you handle that piece when the time comes (sounds like we can kick the can for now).
4. "Release" just means it's for testing a release (compose) and building "release" images (dockerfile) i.e. the build_release script has been run and the container is using a "release" pkg not source.
5. I don't install jruby separately from aspace personally, and I don't believe there's a reason why the top level Gemfile can't be used with either ... so it seemed reasonable to me, but we can take it out if you prefer 👍

**Comment by quoideneuf** [comment]
That all sounds good to me. Re #5 I don't mind leaving it multi-platform, I believe you are right that it shouldn't matter.

**Review by quoideneuf — APPROVED** [review]

**Pull request merged**
