### PR TITLE
Frontend tests

### PR DESCRIPTION
**Pull request by lorawoodford**
Previously, frontend selenium tests existed in two different locations: `frontend/spec/selenium` and `selenium` and could be called by three different build tasks (`frontend:selenium`, `selenium:test`, and `selenium:staff`).  This unites all existing frontend selenium tests into the `frontend/spec/selenium` directory and removes references from the older `selenium` directory.

## Description

- Remove old selenium directory and move relevant files to `frontend/spec/selenium`
- Update build file 
- Ran rubocop across all frontend tests
- Updated non-selenium frontend tests infrastructure to make it parallel that in use for public tests for easier maintenance
- Updated coverage report process (now all coverage reports are generated in `coverage` inside the base directory)
- Confirmed all frontend tests pass

The following work has not been completed and should be addressed in the future:
- Adding frontend tests to Travis builds
- Fixing two broken selenium tests currently skipped with xit
- Adding frontend selenium tests to coverage reports

## Motivation and Context

Ongoing cleanup and maintenance of testing infrastructure.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexduryee** [comment]
I ran the Selenium suite again, and the `merge_and_transfer` specs all failed with `connection refused` errors.  `Accessions can add a rights statement to an Accession` also failed with `NoSuchElementError` for me.

`frontend:coverage` worked as expected!

**Comment by lmcglohon** [comment]
@alexduryee Both Lora and I are not having issues with the selenium tests failing so I am thinking that the reason the tests are failing is because we haven't been cleaning up data from previous test runs in our test setup. I have added a commit that removes the solr index and the test database in the frontend:selenium test suite prior to running new tests, so can you try to run the tests again with the new commit and see how that goes?

**Comment by alexduryee** [comment]
I ran the full Selenium spec suite again, with the same results as before.  However, when I ran the accession and merge_and_transfer specs by themselves, they fully passed!  I'm not entirely sure why adding rights statements to accessions, and merge/transfers, aren't working for me as part of the larger suite but do in isolation.  I wouldn't be surprised if it's due to timeouts while waiting for certain interfaces to load, so I'm willing to approve this PR, since the specs clearly all pass.

**Comment by lmcglohon** [comment]
Yes, I think it is ready to merge as well. Thanks!

**Pull request merged**
