### PR TITLE
Frontend form performance

### PR DESCRIPTION
**Pull request by marktriggs**
Hi there,

Over the past few nights have been having a look into why the edit forms feel slower to load than they used to.  My recollection was that they felt slower after the upgrade to Rails 5.x, so I thought I'd dig around with a profiler.

There wasn't a single culprit, but a couple of changes together got the load times down to 50-60% of what they were and I've included those in  commit 69878aa.

I've also included a minor fix for the backend startup diagnostic message.  I forgot to install the mysql-connector locally and my backend startup failed with an `undefined local variable` error, which was just due to a little typo.

Cheers!
Mark

### CODE REVIEW

**Comment by lmcglohon** [comment]
@marktriggs Thanks so much for this.  We did a little bit of testing and found a definite, immediate improvement in loading speed. Unfortunately, we also saw that loading speed degraded over time/number of requests and, in fact, the application froze after a couple hours with a complex record and these code modifications included. Here’s a link to our initial findings, in case they’re of interest: https://docs.google.com/spreadsheets/d/1I1QgtCwXYD0FBybX0p80VGa3O-AR1JKoKCDwkeiwqCA/edit?usp=sharing

We believe some of the issues could be caused by garbage collection and/or memory leak problems, and this pull request seems to speed up reaching the danger zone, if that suggests anything to you and you’re willing to give it another look.

**Comment by marktriggs** [comment]
Drat!  Thanks @lmcglohon :)  I'll take a look and report back.

**Comment by marktriggs** [comment]
Hi @lmcglohon,

Wow... that's a lot of instances!  I created a resource record locally with 1300 links to unique top containers and ran out of memory in much the same way.

The good news is that the bit of my patch that was increasing memory usage isn't the bit that made the most different performance-wise, so I've dropped that out now.  I've updated this PR with the latest code.  It wasn't using all that much additional memory when I tested it, but my test data could definitely be different to yours, and maybe it was just enough to push it over the edge.

Cheers,
Mark

**Comment by lmcglohon** [comment]
@marktriggs Thanks for the update. We did more testing using the updated PR and continued to see the previous improvement in loading speed. Once we upped the memory to 2G, things continued to look good. We updated the spreadsheet, in case you're interested: https://docs.google.com/spreadsheets/d/1I1QgtCwXYD0FBybX0p80VGa3O-AR1JKoKCDwkeiwqCA/edit?usp=sharing

We are getting ready to put out a new release and have already frozen the code for that so this PR will be in line for consideration for the next release.

**Comment by marktriggs** [comment]
@lmcglohon That's great.  Thanks for putting it through its paces!

**Comment by mark-cooper** [comment]
Gave this a spin, also looking good to me ⭐️

**Pull request merged**
