### PR TITLE
ANW-874

### PR DESCRIPTION
**Pull request by sdm7g**
PUI staff_links link to /resolve/readonly instead of /resolve/edit 

## Description

trivial one line change to public/app/assets/javascripts/smart_staff_links.js
change target link from /resolve/edit to /resolve/readonly 

Documentation and config comments say only: "attempt to add a link back to the staff interface"  : 
doesn't require update as it's not explicit about what link back. 

## Related JIRA Ticket or GitHub Issue

[ANW-874](https://archivesspace.atlassian.net/browse/ANW-874)

## Motivation and Context

/resolve/edit requires edit permission, and fails for users without that repository permission.

## How Has This Been Tested?

manually tested links after rebuild. 

Should not affect anything else.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lmcglohon** [comment]
@sdm7g I believe that there is a check on the user permissions prior to displaying the staff only link. I wonder if we can use that information to check to see if the user has edit privileges and if so, have the link be resolve/edit and, if not, have the link be resolve/readonly?

**Comment by sdm7g** [comment]
@lmcglohon probably possible to do that, but I think going to the view is better UI case. 
 Even before aeon use case made it more of an issue, I always wanted to see the staff view, but didn't want to actually edit in most cases. That seems like the more general case, and if you want to edit, you can hit edit button.   And even when they hit edit, I'm seeing most of our staff users are hitting edit just to be able see all of the fields, to see if something was left unassigned that should have been, or to check what the other possible controlled value entries are. I would be very surprised, from my observation in the wild,  if most of the time this link is used, that it's actually used to edit the item.

**Comment by sdm7g** [comment]
PS: I'll also note that this behavior is very awkward to change in plugin. 
It's an anonymous javascript function that's being fired off on page load by jquery. 
I have an alternate version of the javascript in plugins/local/public/view/layout_head. 
However, I have had to add a delay to when my script is fired off. 
Otherwise, what usually happens is my script runs and then the distribution version from smart_staff_links.js runs and undoes my setting. 
Do you know of any Javascript tricks to do this more deterministically ?

**Comment by lmcglohon** [comment]
@sdm7g Perhaps #1654 instead of this PR?

**Pull request closed without merging**
