### PR TITLE
Expose adding solr params via AppConfig

### PR DESCRIPTION
**Pull request by mark-cooper**

### CODE REVIEW

**Comment by mark-cooper** [comment]
There's an example of the mailing list like this:

```
ArchivesSpaceService.loaded_hook do
  Solr.add_search_hook do |query|
    query.add_solr_param('bq', "title:\"#{@query_string}\"*")
    query.add_solr_param('pf', 'title^10')
    query.add_solr_param('ps', 0)
  end
end
```

This PR won't resolve instance variables. Will look into it.

**Comment by mark-cooper** [comment]
Ok, ready to review (again).

**Comment by lorawoodford** [comment]
@lmcglohon and I discussed beefing up some of the examples offered in the config.rb comments, but otherwise this looks good to me.

**Comment by mark-cooper** [comment]
@cdibella it will apply to both.

**Comment by fordmadox** [comment]
I just tried testing this out.  I was not seeing any changes when I was running the devserver with the master branch (experimenting with changing the "mm" value), so I went ahead and downloaded the 2.3.1 release just for the heck of it.  With the following added to config.rb in a completely vanilla instance of 2.3.1:

AppConfig[:solr_params] = {"q.op" => "AND"}

(is the above correct???)

I ran a search for "miles edwards" (without quotes) in the staff interface, and I got the same results as if I had run a search for "miles AND edwards".

I ran a search for "miles edwards" (without quotes) in the public interface, and I got the same results as if I had a run a search for "miles OR edwards".  And I confirmed that I got the same results in the PUI as the staff interface as long as I changed my query in the PUI to "miles AND edwards".  

So, something definitely is not working for me.  Can this be retested in the PUI with version 2.3.1?  I haven't ventured to try anything other than changing the default q.op value to AND since that's the easiest thing to test and confirm whether it's working or not.

Next, I went ahead and installed the "and_search" plugin that HM developed.  That had the exact same results.  But, I did confirm that when the "and_search" plugin is turned on, then all of the boosts that were recently added to the solrconfig.xml file are ignored (e.g. my first results with the plugin turned on were agent and subject records).  With the plugin turned off, then those boosts work (e.g. my first results were collection records, *not* agent and subject records).  

I then disabled the plugin and re-added the "AND" option to the AppConfig settings.  Just like the plugin, I confirmed that the boosts from the solrconfig.xml file were ignored (because, once again, my top results were agent and subject records).

So, very strange behavior in the PUI; I wonder if it has something to do with the "op" param that always seems to be passed in the URL when a search is performed?  Anything that's set in the application is going to override a default setting, so that's the only thing that I can think of.

All that said, I assume that the AppConfig solr param setting would work with the title boost example that's provided, but I don't see any evidence whatsoever that you can use this technique (or the HM plugin technique) to force an "AND" operator in the PUI (although it does clearly work in the staff interface).  I assume that you could change the solrconfig file to add that value using the "appends" method, but I think that would take away the users ability to ever specify an "OR" operator.

Please let me know if I need to provide any other documentation / examples, but the above results were clear to me just by trying any two-term query in the PUI.

**Comment by fordmadox** [comment]
@mark-cooper , @lorawoodford , @lmcglohon , @cdibella :  just an FYI in case my above comment hasn't been seen yet.  I don't want to add it to JIRA or to a Github issue until others have had a chance to confirm, but it seems quite apparent to me that there are some issues with this approach and the PUI.  i haven't figured out exactly what's going on yet, but adding AppConfig[:solr_params] = {"q.op" => "AND"} does NOT have the expected effect in the PUI, whereas it does in the staff interface.  That said, we should really be going for something a bit more nuanced by using the edismax/dismax parameter mm (similar to what Blacklight does out of the box), e.g. https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/templates/solr/conf/solrconfig.xml#L77

**Comment by lorawoodford** [comment]
Hey @fordmadox just to reassure you that this has not gotten lost!  We all had a long discussion about these very issues yesterday, and are on it.  Any and all input you have to share is appreciated as we're working toward improving this.

**Comment by fordmadox** [comment]
Thanks, @lorawoodford !  I'll keep testing things this week, and provide any other information if I uncover anything.

Right now, I've been tweaking some things in Solr with really good results in a dev instance.  I've added the Krovetz Stemmer, for instance (https://lucene.apache.org/solr/guide/6_6/filter-descriptions.html#FilterDescriptions-KStemFilter; i'd point to the solr 4 docuemntation, but that's so old it's only in PDF form now :)).  Blacklight uses the Porter stemmer by default, which I think is too aggressive of a stemmer.  I'm not sure what's best for ASpace to use by default (if anything), but it's still something that the community needs to talk about, I think.  A group here, led by Alison Clemens, has been creating some "model search cases" to test the PUI (and staff interface), and a good percentage of those require a stemmer to get the expected results.

I'm also a big fan of using a variable mm value, rather than ANDing all query clauses together.

Anyhow, the Solr admin console has been an amazing help to try to figure out what's going on.  Now it's just a matter of getting those settings into the application!

**Comment by trevorthornton** [comment]
I've been trying to make sense of the PUI code and it looks like it's
setting a lot of Solr params at the controller level, which might override
anything specified in the config. For example, it looks like the 'op'
parameter might get set here:
https://github.com/archivesspace/archivesspace/blob/master/public/app/controllers/concerns/searchable.rb#L105
But I could be wrong - it's not really clear what's going on with this code.

On the idea of adding a stemming filter: while this could work well in
specific situations based on locally agreed-upon use cases, it may not be
appropriate as a generalized solution, especially for non-English content.
Also, a stemming filter would need to be added to the schema and applied to
the index as well as the query, which could drastically increase the size
of the index for larger repositories.

**Pull request merged**
