### PR TITLE
Generalized table improvements to core

### PR DESCRIPTION
**Pull request by pobocks**
Implementation of generalized table configuration as described in #1843, as well as specific  implementation of enhancements to the linked records table on the LocationController#show page that exercise the implementation.  Some additional solr fields on top_container objects were required to implement the desired improvements to the table.

## Description
`SearchController#do_search` now takes additional arguments which set display variables and allow for specification of extra columns.  A hash of procs usable as "formatters" is provided, so that output of these columns can be customized.  A number of solr fields are added to support specifically sorting top_containers via indicator, display string, and barcode (there is a combined_indicator field as well, which was provided for a previous implementation of the table, but is left in because it would be useful for a future re-write of the "Manage Top Containers" page that leveraged solr rather than sorting on-page.

Views supporting search results now handle display arguments more consistently.

An additional display setting to hide audit columns is supported now.

A migration which changes update time on all rows in top_container to reindex the top_containers is also included. 

## Related JIRA Ticket or GitHub Issue
Issue #1843

## How Has This Been Tested?
Automated test of the search function with additional argument added to spec file, however it is pended as other search tests are all pended.

Manual testing on local dev environments and in a local built QA environment. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mark-cooper** [comment]
Hi @pobocks

Thx for the PR! @lorawoodford and I will look it over in more detail soon and Christine will want
to check it out from the user perspective.

Some initial feedback on the formatters: I do think formatters should be placed in a dedicated
module so it declutters the controller and they can be more easily tested:

```ruby
module Formatters
  def self.stringify
    proc {|field| proc {|record| record[field].to_s }}
  end
end
# search_controller.rb
SearchHelper::ExtraColumn.new(..., Formatters.send(opts['formatter'].to_sym).call(opts['field']), ...)

# or as methods that take a field arg so only 1 level of proc
module Formatters
  def self.stringify(field)
    proc {|record| record[field].to_s }
  end
end
# search_controller.rb
SearchHelper::ExtraColumn.new(..., Formatters.send(opts['formatter'].to_sym, opts['field']), ...)
```

I think we'll want a test to cover each formatter that is provided as part of aspace, along
the lines of:

```ruby
context "Formatters" do
  it "can stringify a field" do
    field  = 'title'
    record = {'title' => :xyz}
    stringify = Formatters.stringify.call('title')
    # or, with field arg
    stringify = Formatters.stringify('title')

    expect(stringify.call(record)).to eq 'xyz' # or contain, match etc. as appropriate
  end
end
```

**Comment by pobocks** [comment]
Sure thing, I'll see about doing that ASAP.

**Comment by pobocks** [comment]
Some issues with the tests based on my poor understanding of matchers, should be fixed now, ready for a second round of review at y'all's leisure.

**Comment by mark-cooper** [comment]
Hi @pobocks,

It's a small thing but I think moving the Formatter module into SearchHelper makes sense.
We don't really want modules in controllers and they only work with ExtraColumn anyway, which
is already a part of SearchHelper.

In Formatter I'm not sold on the inclusion of method_missing. I think it's probably
better to fail if the Formatter method isn't found rather than revert to stringify
behavior (I think that would confuse me at least =)

Looks like the tests are failing, which I can replicate with:

```bash
./build/run frontend:test -Dexample=SearchController
```

For the first looks like it just needs parens:

```ruby
   it 'returns search results with extra columns correctly' do
-    expect (
-      get :do_search, {'extra_columns': [{'title' => 'uri', 'field' => 'uri', 'formatter' => 'stringify', 'sort_options' => {'sortable' => true, 'sort_by' => 'uri'}}]}
+    expect(
+      get(:do_search, {'extra_columns': [{'title' => 'uri', 'field' => 'uri', 'formatter' => 'stringify', 'sort_options' => {'sortable' => true, 'sort_by' => 'uri'}}]})
     ).to have_http_status(200)
   end
```

Didn't get a chance to pick at the others yet.

**Comment by pobocks** [comment]
Aw, dang, I really thought I'd got the tests fixed already, huh, sorry about that.

Also putting a pin here because I need to add placeholder translations to the other locales.

I'd mildly argue against moving  `Formatter` to `SearchHelper` on the principle that helpers in Rails are considered primarily associated with the view layer rather than the controller, and the calling of formatters is strictly in the controller.  I could see moving _both_ of them out, actually, both feel like they'd more appropriately live in /model to me, but obv y'all have final say since y'all have to deal with the codebase more than me.

Will try to get this all done tomorrow, will hold off on moving Formatter till afternoon, and if I don't hear back I'll move it into SearchHelper.

**Comment by pobocks** [comment]
I think this should do it?

**Comment by mark-cooper** [comment]
@pobocks yeah I think so! Thx for the updates. I'll give it one more look over tomorrow but unless something comes up it's a 👍 from me.

**Comment by mark-cooper** [comment]
@pobocks LGTM. Merging ANW-462 today introduced a couple of conflicts. Do you want me to resolve them or should I leave that to you? The migration can be removed (there's an identical one in place) and your change should be accepted for `frontend/app/views/top_containers/bulk_operations/_results.html.erb` (fixes span).

**Comment by pobocks** [comment]
@mark-cooper Resolved! Merge at will!

**Comment by lorawoodford** [comment]
@pobocks - Frontend events tests are (properly) failing because display of the view/show version of agents records is broken with this change (see screenshot).  I'm trying to sign off here for the day and won't be in tomorrow, but didn't want to head into the weekend with this hanging over me.

image

**Comment by mark-cooper** [comment]
@pobocks these changes should resolve it:

```diff
--- a/frontend/app/views/agents/show.html.erb
+++ b/frontend/app/views/agents/show.html.erb
@@ -112,7 +112,7 @@

         <%= render_aspace_partial :partial => "search/embedded", :locals => {:filter_term => {"rights_statement_agent_uris" => @agent.uri}.to_json, :heading_text => I18n.t("agent._frontend.section.linked_via_rights_statement")} %>

-        <%= render_aspace_partial :partial => "search/embedded", :locals => { :extra_columns => [ "event_type"], :record => @agent, :filter_term => {"linked_record_uris" => @agent.uri}.to_json, :heading_text => I18n.t("event._plural")} %>
+        <%= render_aspace_partial :partial => "search/embedded", :locals => { :extra_columns => [ { "title" => "event.event_type", "field" => "title", "formatter" => "stringify", "sort_options" => { "sortable" => true, "sort_by" => "title" } }], :record => @agent, :filter_term => {"linked_record_uris" => @agent.uri}.to_json, :heading_text => I18n.t("event._plural")} %>
```

Adjust as necessary =)

Also this helps when running the tests independently:

```diff
--- a/frontend/spec/selenium/spec/events_spec.rb
+++ b/frontend/spec/selenium/spec/events_spec.rb
@@ -20,7 +20,7 @@ describe 'Events' do

     @agent = create(:agent_person, names: [name])

-    run_index_round
+    run_all_indexers
```

**Comment by pobocks** [comment]
@mark-cooper Good catch. D'you want me to do them, or do y'all wanna?

**Comment by mark-cooper** [comment]
@pobocks I'll let you do it so if you spot anything off about my suggestions you can correct it as you update (hopefully this will be the final piece of review). Also, if you could fix the broken span in `_results.html.erb` that would be great  (it'll roll in nicely with this PR)!

https://github.com/archivesspace/archivesspace/blob/006b7e4b12e87a121c75e5919f7fd1d1169970b9/frontend/app/views/top_containers/bulk_operations/_results.html.erb#L58

**Comment by pobocks** [comment]
Sorry I let this lay fallow so long, gonna try and get to this today!

**Comment by pobocks** [comment]
@mark-cooper I made the requested changes, but I'm not sure... if the result is correct, or if I properly understand what's supposed to be pulled by which search.

image

I added an acknowledgement event referencing this agent, and it shows up in Linked Records but not events - could you maybe give me some context on what that property the search is meant to return is representing?  If not, I can dig through the code and see if I can figure it out, but I'm a tad overbooked today.

**Comment by mark-cooper** [comment]
@pobocks I'd see if that happens on master because you may just be encountering existing (perhaps counter-intuitive) behavior and what you do in the ui may not be replicating what is done in the tests.

**Comment by pobocks** [comment]
This should be good to go, maintains existing behavior.

**Pull request merged**
