### PR TITLE
Core Code Plugin Support - Changes for 4.0

### PR DESCRIPTION
**Pull request by jdshaw**
- properly render plugin layouts inline for both staff and public frontends and public pdf exports
- allow plugins to add their own shared/templates equivalents - due to changes in `ActionView::PartialRenderer render` method
- fix public pdf locals for digital object links

## Description

Some plugin partials were not rendering inline properly. Additionally, changes to `ActionView::PartialRenderer` necessitated the inclusion of an additional plugin file (`frontend/views/_shared_templates.html.erb`) to allow plugins to add their own templates for the frontend.

Also fixes local variable for plugins which use a plugin supplied `_pdf_digital_object_links` partial
## How Has This Been Tested?

Local tests. Mac OS 14, MariaDB 10.11.4, Solr 8.11.2
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by thimios** [comment]
@jdshaw thanks for the PR, I am in the process of reviewing it. Could you point me to the plugins that are being fixed by these changes?

**Comment by jdshaw** [comment]
@thimios The title isn't the best. I'll changed it to reflect that this PR fixes core code *support* for plugins.

**Comment by jdshaw** [comment]
An example of a plugin that would have broken without these changes: https://github.com/dartmouth-dltg/local_contexts_projects.

**Comment by thimios** [comment]
@jdshaw that's awesome! It would be very helpful to know which specific plugins you are working with that motivated these changes. I would like to test them out as part of reviewing these changes.

**Comment by jdshaw** [comment]
@thimios I've been updating the plugins that I support (list below) and that's how I've been identifying the core changes that needed to be made. For each plugin, if there were changes needed for 4.0, there is a branch labeled `as-4.0` (see the local contexts plugin for example) with the plugin specific changes. 

The local contexts plugin is a good example since it does all the things: adds shared templates and includes some PUI view additions - like those for the PDF, upper records, and welcome.

Let me know if you see anything wonky or have a better way to approach any of the changes.

1. Local Contexts: https://github.com/dartmouth-dltg/local_contexts_projects
2. Harmful Content: https://github.com/dartmouth-dltg/aspace_content_warnings
3. Reparative Descriptions: https://github.com/dartmouth-dltg/aspace_reparative_descriptions
4. PUI Analytics: https://github.com/dartmouth-dltg/aspace_analytics
5. OmniAuth CAS: https://github.com/dartmouth-dltg/aspace-omniauth-cas
6. Custom Localizations: https://github.com/dartmouth-dltg/aspace_custom_localizations
7. Container Labels: https://github.com/dartmouth-dltg/container_management_labels
8. PUI Sitemap: https://github.com/dartmouth-dltg/aspace_sitemap
9. Custom Restrictions: https://github.com/dartmouth-dltg/aspace_custom_restrictions_and_context
10. Search Modifications: https://github.com/dartmouth-dltg/aspace_search_modifications

**Comment by jdshaw** [comment]
I should note that the local contexts plugin is the most complex and requires a bit of config and knowledge of local contexts to get setup. The harmful content plugin is self contained and also relies on  most of the changes.

**Review by thimios — APPROVED** [review]

**Comment by thimios** [comment]
@jdshaw looks good to me, could you rebase on master (ci has been updated so you should get a green run then). Could you also squash all the changes into a single commit before merging?

**Comment by jdshaw** [comment]
Rebased. Will squash and merge when the tests complete.

**Comment by jdshaw** [comment]
@thimios Looks like there are some issues with the Accessibility tests. I'm assuming that's upstream of any changes I made since there's nothing in here that should be affecting accessibiity.

**Comment by thimios** [comment]
> @thimios Looks like there are some issues with the Accessibility tests. I'm assuming that's upstream of any changes I made since there's nothing in here that should be affecting accessibiity.

@jdshaw there is flakiness on those, we are working on fixing it. Go ahead with squashing and I will have to rerun the accessibility specs a couple of times to get them green. Thanks!

**Pull request merged**
