### PR TITLE
fix GITHUB_TOKEN secret

### PR DESCRIPTION
**Pull request by quoideneuf**
Fixes an incorrect GitHub Actions secret reference, and adds an option to fetch stats by pushing to `fetches-download-stats-on-push`. Also includes last month's download.

### CODE REVIEW

**Review by brianzelip — COMMENTED** [review]
In looking at the [ad-m/github-push-action docs](https://github.com/ad-m/github-push-action#example-workflow-file), I see they set `persist-credentials: false` during the checkout step, which impacts the `secrets.GITHUB_TOKEN` used in the Push changes step.

Were you able to run the new workflow and see it work as expected?

**Review by brianzelip — COMMENTED** [review]
Also, I don't have access to the repo's settings, so I can't review the permissions for the `GITHUB_TOKEN` as described in [the docs](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token).

**Comment by quoideneuf** [comment]
It appears to work in my repository, but I can't say I know for sure that it will work in this one. I hope so!

**Review by brianzelip — APPROVED** [review]

**Comment by brianzelip** [comment]
This just needs rebasing w/ master

**Pull request merged**
