### PR TITLE
Update lcnaf service

### PR DESCRIPTION
**Pull request by quoideneuf**

### CODE REVIEW

**Comment by cfitz** [comment]
Ah, great, is this working now? LOC has been having major problems last month or so..

**Comment by quoideneuf** [comment]
@cfitz - I think so - it's hard to know what's going on with the OCLC service - I think it went offline a few months ago, and that's when people reported the plugin not to be working. When I checked last week it was there and the plugin seemed to work fine. But I added the LOC service as an option anyway, and included a message letting the user know the services may or may not be online. There's also better error handling for when the services are offline. I think there are some separate issues pertaining to usability as well but it would be nice to get some feedback about how people want to use this before getting into that.

**Comment by sdm7g** [comment]
On Feb 27, 2015, at 8:08 AM, Brian Hoffman <notifications@github.com> wrote:

> @cfitz - I think so - it's hard to know what's going on with the OCLC service - I think it went offline a few months ago, and that's when people reported the plugin not to be working. When I checked last week it was there and the plugin seemed to work fine. But I added the LOC service as an option anyway, and included a message letting the user know the services may or may not be online. There's also better error handling for when the services are offline. I think there are some separate issues pertaining to usability as well but it would be nice to get some feedback about how people want to use this before getting into that.
> 
> —
> Reply to this email directly or view it on GitHub.
> 



My impression from that email was that the OCLC service is not officially supported: 
http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2015-January/001048.html

so perhaps that options should just be removed and use only LOC. 

In which case it would be simple to add another option and also allow subject record imports. 
( If you change the URL to http://id.loc.gov/authorities/subjects from http://id.loc.gov/authorities/names
  the search actually works with the existing plugin, but the selected record doesn’t import as it’s not an agent.  ) 
i.e. turn it from a LCNAF importer into a LC Authority importer. 


The interface for selecting when there are multiple return items from the search is pretty hard to navigate. 
The info that is displayed in the small boxes is not the info needed to choose the right one, so you have
to select each box and expand it to see the contents. It would be better to display a more informative summary
line or two instead.  Since the LOC search site handles this display better, another option would be
to allow import by dropping in a LOC authority URL . You’ve got to have two browser windows open, but
it avoids having to download the MARC from LOC search to desktop and then import it into ASpace. 
( The importer would need to swap the file extension from ‘.html’  to ‘.marcxml.xml’  ) 


We would like it if it assigned the LOC URI  or the id from @tag=“001”  to Authority ID. 
I’m not sure which would be the more proper value, but URI would be handier so you could 
go to the LOC authority record right from the subject / agent resource in ASpace. 


I’m not sure, but there seems to be some inconsistency in assigned sources in the controlled vocab lists,
backend/app/converters/lib/marcxml_base_map.rb  (which has it’s own list) and the LCNAF plugin. 


— Steve Majewski

**Comment by sdm7g** [comment]
I’m not familiar with the editor code, so I don’t know if this would be possible, but the best option would be:
IF a recognized URL was entered in Authority ID, then offer to import and auto populate the rest of the 
subject or agent record. 

I am told that Getty has an API for Art & Architecture authority lookup, and that MESH doesn’t yet
have one but is working on one, so maybe initially support http://id.loc.gov/ , and have a mechanism
to add plugins for other URL schemes. 

In View mode: IF Authority ID is a URI, then display it as a clickable (open other) link.  

— Steve.

**Comment by quoideneuf** [comment]
@sdm7g - I think these are good points and will raise the idea of expanding to include subjects and shutting down the OCLC option. Also am aware of the usability issues but will merge this in order to triage and save improvements for later. It would be good to have more info about how people want to use this - i.e., what fields they want to search on, what it would be useful to display in the results, etc.

**Comment by sdm7g** [comment]
Agree:  Get stable changes into 1.1.2 release. 
It would be nice to get the feature to set Source URI from import in next release if possible. 
( I don’t know if that requires further discussion. ) 
Adding subjects and dropping OCLC should probably go into a new, renamed plugin,
and give people the option of which to select. 

— Steve.

**Pull request merged**
