### PR TITLE
Add missing badges for accessions and digital objects and wire them up

### PR DESCRIPTION
**Pull request by mark-cooper**
https://archivesspace.atlassian.net/browse/ANW-211

### CODE REVIEW

**Comment by sdm7g** [comment]
Clicking on the digital_objects badge does not append `?limit=digital_object` parameter and so all objects are shown.  From a quick look, I'm guessing that the `<form>` element containing that badge requires a hidden input to be added with this param.

**Comment by sdm7g** [comment]
This seems to work for me:

```
index 9b2d4d371..b1c2c1763 100644
--- a/public/app/views/repositories/_badge.html.erb
+++ b/public/app/views/repositories/_badge.html.erb
@@ -9,6 +9,7 @@
      <% when 'record' %>
       <i class="fa fa-files-o fa-4x"></i>
      <% when 'digital_object' %>
+        <input type="hidden" name="limit" value="digital_object" />
       <i class="fa fa-file-image-o fa-4x"></i>
      <% when 'accession' %>
       <i class="fa fa-file-text-o fa-4x"></i>

```

**Comment by mark-cooper** [comment]
@sdm7g I see. I had no a.objs in my test db, and that happens because of:

https://github.com/archivesspace/archivesspace/blob/master/public/app/controllers/objects_controller.rb#L23

The coupling of a.objs and d.objs I'm not too sure about in general ... but what's done is done 🏖 

I'll push an update. 👍

**Comment by sdm7g** [comment]
Sorry about all of the duplicated redundant comments: After adding initial comments, I realized commenting as a reviewer was a different operation, and after doing that, the additional **view changes** button made it seem like there was a more direct way to add that patch -- still not sure what is the preferred method.

**Pull request merged**
