### PR TITLE
might need to readd the table structure so that db:nuke task works on my...

### PR DESCRIPTION
**Pull request by cfitz**
db:nuke might need to have some of the down migrations to complete. fer travis.

### CODE REVIEW

**Comment by quoideneuf** [comment]
@cfitz - thanks, I meant to go back and do this...sorry to be so sloppy.

**Comment by cfitz** [comment]
@quoideneuf  heh, actually not sure it's working...tweaking it a bit now. I didn't know that the db:nuke actually did rollbacks either.

**Comment by cfitz** [comment]
@quoideneuf  I think that does it now. just curious if there was a reason not to drop the import_job table?

**Comment by quoideneuf** [comment]
@cfitz - no,  no reason - I just forgot.

**Pull request merged**
