### PR TITLE
ANW-1388 Add subject merge api examples

### PR DESCRIPTION
**Pull request by lorawoodford**
Adds shell and python examples to the API documentation for the merge subjects endpoint.  The python example is directly copied from what was supplied in JIRA.

## Related JIRA Ticket or GitHub Issue

https://archivesspace.atlassian.net/browse/ANW-1388

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by quoideneuf — APPROVED** [review]
😃 🐍

**Comment by crugas** [comment]
@quoideneuf Just FYI, I updated the JIRA awhile back (https://archivesspace.atlassian.net/browse/ANW-1388?focusedCommentId=37913) to add some comments in the python code to make it easier for people to understand the example. If this would be better to add after 3.2.0 release, just let me know and I can make a small pull request to update it.

**Comment by quoideneuf** [comment]
@crugas - It is fine to add anytime. We aren't accepting any more changes to the 3.2.0 release unless they are necessary, but you can submit to the master branch now.

**Comment by crugas** [comment]
@quoideneuf Made a pull request here: https://github.com/archivesspace/archivesspace/pull/2632. Let me know if you have any questions or need me to redo the code/pull request. Thanks!

**Pull request merged**
