### PR TITLE
ANW-942: Display suppressed status in large tree

### PR DESCRIPTION
**Pull request by brianzelip**
[ANW-942](https://archivesspace.atlassian.net/browse/ANW-942)

## Screenshots (if appropriate):

ANW-942-suppressed-label

ANW-942-circle-icon

ANW-942-eye-icon

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by quoideneuf** [comment]
@brianzelip Sorry for taking so long to get to this. Here is a commit that will make the logged node object in the JS have the `suppressed` property.  I'm not sure if that will be enough to complete the issue but let me know how it goes.
https://github.com/archivesspace/archivesspace/commit/bc2c7d90b26ffcb7e190d4fc2c596c448a42fb75

**Comment by quoideneuf** [comment]
@brianzelip Is this ready for review? Let me know if there's anything I need to follow up on.

**Comment by brianzelip** [comment]
@quoideneuf no, I just needed to write the test. Now it's ready for review.

Also, in the ticket there was a question about whether the full 'suppressed' label would clog up the tree view.  They suggested perhaps using a different color to identify suppressed records. I think labels and icons are better differentiators than colors. This PR implements the 'suppressed' label as is used elsewhere in the app -- it doesn't seem to me to clog up the tree interface. I've also included screenshots of leveraging icons that already exist in our stack -- see screenshots above. I can change the markup to whichever style is deemed best.

**Review by quoideneuf — APPROVED** [review]
👍

**Pull request merged**
