### PR TITLE
Handle timeouts from Solr

### PR DESCRIPTION
**Pull request by cfitz**
This attempts to handle timeouts from Solr by logging them as error but
not stopping the indexer round. Timeouts can cause a problem where the
index round fails and enters into an infinite loop.

## Description
I've seen a few cases where an institution has an under-performing Solr server that's trying to keep up with the indexer. During a large re-index, the Solr server might send timeouts, which get raised as errors in the indexer code. This casuses the index batch to fail, which the indexer will then restart, causing an un-ending index loop that will continue until the app runs out of memory. 

## Motivation and Context
This attempts to solve some issues that organizations with limited solr experience have. 

## How Has This Been Tested?
Rspec tests included in the indexer test code. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lmcglohon** [comment]
@cfitz should this also include the realtime indexer?

**Comment by cfitz** [comment]
@lmcglohon yeah, this will include the realtime indexer, but I think that is much less common?

**Comment by cfitz** [comment]
Hi, 

in implementing this, I've found out there's actually a few different responses that can be returned on a time out.
Might it be better to just have the indexer log solr errors and keep on trucking rather than raising a error ( and hence aborting the batch ) when it gets an error? 
It's not ideal, but the "indexer stuck in an infinite loop" does  seem to be a common problem for some institutions...and it's hard to detect unless you know what you're looking for.

**Comment by lmcglohon** [comment]
@cfitz I like the idea of the indexer logging errors and moving on to the next record. I believe that is the main reason for the "indexer stuck in an infinite loop" problem. This PR will not make it in the next release (coming out next week) so would you like to add your enhanced solution to this PR for inclusion in the first release of 2019?

**Comment by cfitz** [comment]
@lmcglohon ok will rework this. 
No worries about the release. I put this in as a plugin for them.

**Comment by lmcglohon** [comment]
@fitz Thanks Chris!

**Pull request closed without merging**
