### PR TITLE
Also resolve container profiles

### PR DESCRIPTION
**Pull request by mark-cooper**
Full disclosure: haven't tested this yet. But believe it's needed same as for:

https://github.com/archivesspace/archivesspace/commit/2f6e2997b9785796ad41b54e69c8875e066abd11

Error (as of 06/20):
http://dev.archivesspace.org/oai?verb=ListRecords&metadataPrefix=oai_ead

### CODE REVIEW

**Comment by mark-cooper** [comment]
@lmcglohon tested and not doing the business. Needs a deeper dive ...

**Comment by marktriggs** [comment]
@mark-cooper I've got a fix for the EAD issue in the works so I'll incorporate your changes here too.  New PR forthcoming!

**Comment by lmcglohon** [comment]
Closing this because it was taken care of in https://github.com/archivesspace/archivesspace/pull/867.

**Comment by mark-cooper** [comment]
:star:

**Pull request closed without merging**
