### PR TITLE
ANW-172: Add all dates to ao and do records h2

### PR DESCRIPTION
**Pull request by lorawoodford**
Adds all available dates to the headings of archival object and digital object component records in the staff side and, if published, public side interfaces.

## Description

Modifies the archival object and digital object component models to include all dates in the autogenerated record display string.  Because this behavior only happens on create or update from JSON, changes to these models only impacts newly created/updated archival components, therefore migration 132 has also been added to identify and, via information stored in the database, recreate these display strings to address previously created archival components.  Additionally, behavior has been added to prepend dates with a date_type of bulk with "bulk: " in the new record headings.  Translations were also added for this prepended bulk label; however, because translations aren't available to migrations a default of "bulk: " has been set for existing headings.

## Related JIRA Ticket or GitHub Issue

Partially completes https://archivesspace.atlassian.net/browse/ANW-172. See also #1845 for display of multiple dates in resource/digital object trees.

## How Has This Been Tested?

Existing archival object backend spec updated; new digital object spec added.

## Screenshots (if appropriate):
Staff side:
image

PUI:
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by brialparker** [comment]
Hey @sdm7g - I have some unexpected capacity today and thought I'd try and nab an extra PR - have your started work on this or would it be okay for me to reassign to myself? Thanks!

**Comment by sdm7g** [comment]
I was about to start on it after lunch, but you’re welcome to take it if you have time. — Steve

**Comment by brialparker** [comment]
I'll take it - looks like you did a bunch already today!

**Comment by brialparker** [comment]
@lorawoodford I'm getting the dates into the h2 for aos, but not for dos.
digital_object_screenshot 

I know you're waiting on this in order to merge another PR, so I'm going to dig deeper later tonight.

**Comment by brialparker** [comment]
@lorawoodford  JUST KIDDING - I misunderstood and didn't catch digital object _component_ which does pull dates. Is there a reason we are not pulling dates for the digital object up to h2 as well? Or is all of this just sailing right over my head today?

**Pull request merged**
