### PR TITLE
ANW-783: Fix linking issues in subject and agent records

### PR DESCRIPTION
**Pull request by andrew-morrison**
When viewing subjects in the staff interface, the "Linked Records" section lists all the resources, archival objects, etc which have been associated with the subject. But when there are duplicate subjects (e.g. same title/term but different sources) both subjects list the same records. The same can happen for agents.

## Description
The problems is the "Linked Records" section is rendered by a call to the _search/embedded_ template, which searches the "subjects" Solr index field for records matching the title of the subject. Searching for the subject's URI instead will return accurate results: only the records which have actually been linked to the subject. This requires creating a new Solr index field called "subject_uris" and modifying the indexer to populate it.

The fix for agents is the same except an "agent_uris" Solr index field already exists.

## Related JIRA Ticket or GitHub Issue
https://archivesspace.atlassian.net/browse/ANW-783
https://archivesspace.atlassian.net/browse/ANW-841

## How Has This Been Tested?
This fix has been working in a plug-in on a production 2.5.1 system for six months.
I have made the same modifications to a development system and tested manually (creating duplicate subject/agent records, linking them to different resource records, then verifying that only the correct ones are listed for each). Running the test suites returns no failures.

## Screenshots (if appropriate):
N/A

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lorawoodford** [comment]
Hi @andrew-morrison ,

Just wanted to leave a quick note to (belatedly) thank you for this (and your other great contributions!).  We've been moving a bit slower of late as we've been preparing a release candidate slated to go out quite soon, but I hope to have this reviewed by early next week at the latest.  Thanks!

**Comment by lorawoodford** [comment]
This looks great @andrew-morrison , but I'd like to make one addition here.  As this stands, it will require users to initiate a full reindex in order to pickup the addition of the subject_uris to the parent archival record types (accessions, resources, etc.).  We typically try to avoid shipping new releases with a full reindex requirement, and get around that by adding in db migrations to do targeted reindexes as part of the `setup-database.sh` process.

I have a working migration written up here, so am happy to push that to your fork prior to merging, but need permissions to add to your fork to do so.  That can be done by following these steps:  https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Alternatively, you can yourself add the following to `common/db/migrations/130_reindex_linked_records.rb`:

```
require_relative 'utils'

Sequel.migration do

  up do
    $stderr.puts("Triggering a reindex of all archival records linked to subjects")

    ['accession', 'archival_object', 'resource', 'digital_object', 'digital_object_component'].each do |table|
      subject_rlshp = self[:subject_rlshp].exclude("#{table}_id": nil).map{|rlshp| rlshp[:"#{table}_id"]}.uniq
      subject_rlshp.each do |r|
        self[:"#{table}"].where(id: r).update(:system_mtime => Time.now)
      end
    end
  end


  down do
  end

end

```

One note here: We're in a bit of a code freeze while waiting for the next release to go out, so I can't 100% promise I won't need you/someone to go back and renumber this migration if a 130 migration is necessitated during the release candidate testing phase.

With this change (however you want to handle it), I'm happy to merge this once the code freeze is over.

Thanks!

**Comment by andrew-morrison** [comment]
I would enable "Allow edits from maintainers" but that checkbox does not appear on this or any of the pull requests I have submitted. I can't find any settings in my GitHub account, the Bodleian organization account, or our fork which would explain it. Maybe GitHub user support will be able to explain it, but in the meantime I've copied and pasted your database migration into a new file at the path specified.

**Comment by lorawoodford** [comment]
Thanks @andrew-morrison .  Merged!

**Pull request merged**
