### PR TITLE
ANW-799: allow users with admin privs access to system_information page

### PR DESCRIPTION
**Pull request by avatar382**
## Description
Allow users with admin privs to access system_information page
## Related JIRA Ticket or GitHub Issue
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-799

## How Has This Been Tested?
manual and unit testing

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by donaldjosephsmith** [comment]
@avatar382 looks like this change may have impacted the tests in `system_information_spec.rb`, as I'm seeing the same failures running the tests locally.

**Comment by mark-cooper** [comment]
I'm generally reluctant to advocate for more AppConfig but I believe it would be prudent if this is going ahead to add something like `AppConfig[:system_info_restricted_to_global_admin]`. AppConfig, being a ruby file, is very broad, open ended and general purpose and particularly in shared environments (such as with hosting) it could be a security concern to have this be available to every admin user in the system.

**Comment by cdibella** [comment]
This is pending @avatar382 adding a configuration option (requested on the JIRA and discussed with him directly).

**Comment by thimios** [comment]
@avatar382 as discussed this needs changes on the specs to pass

**Pull request merged**
