### PR TITLE
ANW-1349 Remove Lodash dependency

### PR DESCRIPTION
**Pull request by brianzelip**
## Description

The use of Lodash is unnecessary at this point, and causing some failing tests.

This PR removes Lodash source files and requirements, and replaces 21 Lodash functions across 5 files with javascript and jquery equivalents.

## Related JIRA Ticket or GitHub Issue

[ANW-1349](https://archivesspace.atlassian.net/browse/ANW-1349)

## How Has This Been Tested?

Manual visual testing, see below.

## Screenshots (if appropriate):

The following screenshots demo the successful lodash replacements.

Apply notes order functionality (notes.crud.js and notes_merge.crud.js)

notes-applyNotesOrder

Readmore functionality (public/app/assets/javascripts/readmore.js.erb)

readmore

Repository note order preferences functionality (frontend/app/assets/javascripts/preferences.js)

note-order-pref

RDE template functionalities (frontend/app/assets/javascripts/rde.js)

Apply RDE template

apply-rde-template

Save RDE template

save-rde-template

Render the remove RDE templates table

render-remove-rde-templates-table

Load RDE template options and data

load-rde-template-options-and-data

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by quoideneuf** [comment]
Looks great - I just opened a PR on your repo @brianzelip with a commit to remove the actual lodash files.

https://github.com/brianzelip/archivesspace/pull/3

**Comment by brianzelip** [comment]
@quoideneuf Looks like the volatile tests are passing now. This PR is almost ready.

I opened up #2359 to see the test responses when only lodash requires and source files are rmoved.

**Comment by brianzelip** [comment]
This is ready to be elevated from draft status.

**Review by quoideneuf — COMMENTED** [review]
👍

**Review by quoideneuf — APPROVED** [review]

**Pull request merged**
