### PR TITLE
ANW-172 Show all sub record dates in tree

### PR DESCRIPTION
**Pull request by brianzelip**
## Description
This PR adds all dates to the archival objects tree subrecord view, including with 'bulk' prepended when appropriate, in both staff and public interfaces.

screenshot of ANW-172 solution showing all dates in staff tree subrecord view

screenshot of ANW-172 solution showing all dates in public tree subrecord view

## Related JIRA Ticket or GitHub Issue
[ANW-172](https://archivesspace.atlassian.net/browse/ANW-172)

## Screenshots (if appropriate):
See above

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [X] All existing tests passed.

### CODE REVIEW

**Comment by brianzelip** [comment]
PUI update, as mentioned in the ticket comments, is in the works.

**Comment by brianzelip** [comment]
The more I think about it, up to this point, only Tree view has been updated. I assume the record title needs to be updated too (ie: in the screenshot above, the title below the "Edit" button and above the "Basic Information" heading) - is this correct @cdibella ?

**Comment by lorawoodford** [comment]
Hey @brianzelip - Yep, I've got a branch (not yet pushed) that does exactly that that is working fine.  However, I've hit a snag in that I can't think of a seamless way to retroactively fix/update all pre-existing records since those header display strings are only generated with an update from json.  I'm hoping to return to that branch next week, and will plan on merging that and this at the same time.  Thanks for getting this half done, though!

**Comment by brianzelip** [comment]
PUI tree title strings now show all dates as well. See new screenshot added to initial PR post above.

**Comment by brianzelip** [comment]
I’ll check it out, thanks Lora!

**Comment by lorawoodford** [comment]
Heya @brianzelip - We're looking at an anticipated code freeze starting next Friday (5/1) as we prepare for a mid-May release.  Do you think you'll have time to address this one outstanding change (pre-pending bulk as explained above)?  Feel free to ping me here or on Slack with questions!  Thanks as always!

**Comment by brianzelip** [comment]
Hi @lorawoodford - have a look at the updates. The screenshots above have been updated to reflect the 'bulk: ' prepend.

**Comment by brianzelip** [comment]
ping @lorawoodford

**Pull request merged**
