### PR TITLE
adding schemas to slate api docs

### PR DESCRIPTION
**Pull request by cfitz**
http://cfitz.github.io/archivesspace/api/

### CODE REVIEW

**Comment by mark-cooper** [comment]
1.1mb transferred, 44s load time for me. That's too horribly slow I think, feels unusable ... particularly given the schemas can be accessed via the api (which is documented):

http://archivesspace.github.io/archivesspace/api/#get-schemas

What do you think? =)

**Comment by cfitz** [comment]
yeah....it's pretty bad.

also this:
https://github.com/blog/2228-simpler-github-pages-publishing
might be time to redo some of this.

**Comment by cfitz** [comment]
Hi
So i just looked at this...yeah the load time was pretty bad because of the docson widget having to load for all the schemas. Not so bad if your browser caches it, but not great.

I dumped the docson widget and just spit a table with the schema itself in the code pane. 
http://cfitz.github.io/archivesspace/api/

I think that works better? Sorry this PR was something I slapped together b/c someone said they had a workshop that needed it...

**Comment by mark-cooper** [comment]
It's faster =)

373kb, 7s, but that's vs. 90kb, 2s.

Also it looks like some YFM has leaked into the page and the Errors section is gone:

http://cfitz.github.io/archivesspace/api/ vs. http://archivesspace.github.io/archivesspace/api/

Having said that I don't think there's an issue with how it is now. It's fast and has all the information, including how to access the schemas via the api.

**Comment by cfitz** [comment]
ugh.. there was an error that caused a problem with markdown. fixed that.
http://cfitz.github.io/archivesspace/api/

But yeah...might be alright now.

**Pull request closed without merging**
