### PR TITLE
ANW-1593, ANW-2157: Customize staff and public favicons

### PR DESCRIPTION
**Pull request by brianzelip**
This PR:

- Updates the favicon set for both frontend and public with higher quality images that were cut from the recently new ArchivesSpace logo svg
- Breaks out each app's favicon markup into its own partial for easy favicon customization via plugin
- Adds a default `AppConfig` option for whether or not to show favicons in each application; each defaults to `true`.
- Also closes [ANW-1593](https://archivesspace.atlassian.net/browse/ANW-1593)

[ANW-2157](https://archivesspace.atlassian.net/browse/ANW-2157)

[ANW-2157]: https://archivesspace.atlassian.net/browse/ANW-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ANW-1593]: https://archivesspace.atlassian.net/browse/ANW-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by brianzelip** [comment]
@jdshaw Have you ever successfully included image assets in PUI plugins? The favicons that I've included here in the PUI plugin assets directory break, while the frontend images work as expected.

I checked through [your list of plugins](https://github.com/archivesspace/archivesspace/pull/3329#issuecomment-2414412453) but didn't see any pui images.

**Comment by jdshaw** [comment]
@brianzelip  I've successfully used `asset_path()` like in the following in 3.x. I have **not** tested in 4.0 since my use case is for our heavily customized PUI which I have not started to work on since its not a public plugin.

`" />` or `<link href="<%= asset_path('my_favicon.png') %>" />`

I've used this in two overidden views: `views/layout/application` & `views/pdf/titlepage`

I wonder if its something in the Rails render method that's being weird since that had some updates for v6 that needed some changes (like in my pull request: https://github.com/archivesspace/archivesspace/pull/3329/files). However, I now wonder if there's something else going on that might mean we don't need to explicitly render inline for those plugin views in the pull request.

**Comment by jdshaw** [comment]
As a note, if I prefix the plugin path with `assets/` like 

```
<link rel="icon" type="image/png" href="<%= asset_path('assets/favicon.png') %>">
<link rel="icon" type="image/svg+xml" href="<%= asset_path('assets/favicon.svg') %>">
```

Then we're good. I'm gonna check to see if there's something in the core code that supports plugin assets (if there is anything?) that needs an update

**Comment by brianzelip** [comment]
Thanks @jdshaw - this PR is now working.

**Review by donaldjosephsmith — APPROVED** [review]

**Pull request merged**
