### PR TITLE
ANW-1364: adding CSV download support for jobs, location profiles and collectio…

### PR DESCRIPTION
**Pull request by avatar382**
## Description
adding CSV download support for jobs, location profiles and collection mangement

## Related JIRA Ticket or GitHub Issue
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1364

## How Has This Been Tested?
in browser and unit testing

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by avatar382** [comment]
Found this commit, and it should fix some of the issues addressed in this PR. Was this ever merged? Looks like Github isn't sure.
https://github.com/archivesspace/archivesspace/commit/b62d09fde021b00a73b62ba1f7d9df02a793957d

**Comment by avatar382** [comment]
https://github.com/archivesspace/archivesspace/issues/1910

**Comment by avatar382** [comment]
The issues with classifications CSV export turned out to be caused by unrelated issue (the missing fields were not indexed) and addressed in #2797.

Removed all work relating to classifications CSV export from this PR, so it's focused on adding CSV functionality to jobs, location profiles and collection management.

**Review by quoideneuf — CHANGES_REQUESTED** [review]
It seems like there is already a pattern in place for fetching results from the api and streaming them out as css. See:
https://github.com/archivesspace/archivesspace/blob/master/frontend/app/controllers/search_controller.rb#L78-L82
and:
https://github.com/archivesspace/archivesspace/blob/master/frontend/app/helpers/export_helper.rb#L3-L13
Couldn't the same solution be used for the additional controllers?

**Comment by avatar382** [comment]
> It seems like there is already a pattern in place for fetching results from the api and streaming them out as csv. See: https://github.com/archivesspace/archivesspace/blob/master/frontend/app/controllers/search_controller.rb#L78-L82 and: https://github.com/archivesspace/archivesspace/blob/master/frontend/app/helpers/export_helper.rb#L3-L13 Couldn't the same solution be used for the additional controllers?

Thanks for pointing that out -- I had trouble with the existing pattern before, but how it works is more clear now. Updated PR to remove duplication and to use the existing pattern.

**Review by quoideneuf — APPROVED** [review]
👍

**Pull request merged**
