### PR TITLE
Subrecord enhancements

### PR DESCRIPTION
**Pull request by lorawoodford**
Includes two commits from the larger #1896 written by @payten and funded by Queensland State Archives.

- 487e2ba65131a6ebe7e0998ce35a4f15a88f21ed: Focus the first VISIBLE form element after adding a new nested subrecord form
- ffc1fbbb2f7ec931ae6f5a06569db67a4e0cf598: Show count of hidden subrecords via too_many_subrecords_template

## Description

Includes modifications to the staff-side subrecord javascript and forms, including:

- Focus the first VISIBLE form element after adding a new nested subrecord form since some subrecord forms have hidden form elements; and, 
- Adding the count of hidden subrecords via the too_many_subrecords_template.

## How Has This Been Tested?

Existing tests pass, manually confirmed behavior.

## Screenshots (if appropriate):

ffc1fbbb2f7ec931ae6f5a06569db67a4e0cf598 adds the count of hidden subrecords in parens at the end of the click_to_show statement:

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by milesnimer** [comment]
Functionality appears to working correctly, both for focus in new subrecords and inclusion of number in label for hidden subrecords.

**Comment by mtkidd** [comment]
Checked this in the AS Test environment and the count for hidden subrecords does display.

**Comment by jdshaw** [comment]
Checked in test. First form element is focused and count of sub-records does display.

**Comment by erussey** [comment]
Working as expected in ArchivesSpace test environment.  Count of hidden subrecords displays as described.

**Pull request merged**
