### PR TITLE
ANW-429 Exports update 1

### PR DESCRIPTION
**Pull request by mark-cooper**

### CODE REVIEW

**Comment by mark-cooper** [comment]
This is predominantly Rubocop cleanup of these files with a few exceptions:

- updated agents api export path to reflect record type pattern
- added the expected namespaces to the xml export
- updated leader to include 'i' in pos 18
- removed namespaces from marc auth xml for specs xpath

**Comment by lorawoodford** [comment]
@mark-cooper Merging this will break the ability for folks to export MARC auth from the staff interface.  Looks like there's a `download_marc_auth` method in `frontend/app/controllers/exports_controller.rb` that will need to be updated to work with the new export paths.  Otherwise you get:

```
[java] I, [2021-02-08T09:28:52.964541 #27906]  INFO -- : Completed 500 Internal Server Error in 29ms
[java] 
[java] 
[java] F, [2021-02-08T09:28:52.965920 #27906] FATAL -- :   
[java] F, [2021-02-08T09:28:52.966027 #27906] FATAL -- : NoMethodError (undefined method `[]' for nil:NilClass):
[java] F, [2021-02-08T09:28:52.966112 #27906] FATAL -- :   
[java] F, [2021-02-08T09:28:52.966202 #27906] FATAL -- : app/controllers/exports_controller.rb:83:in `block in download_export'
[java] app/controllers/exports_controller.rb:81:in `download_export'
[java] app/controllers/exports_controller.rb:66:in `download_marc_auth'
```

**Review by lorawoodford — CHANGES_REQUESTED** [review]
Update `download_marc_auth`

**Comment by mark-cooper** [comment]
@lorawoodford updated 👍

**Review by lorawoodford — APPROVED** [review]

**Pull request merged**
