### PR TITLE
Updated API docs with general information section.

### PR DESCRIPTION
**Pull request by pobocks**
This is a strawman, basically a very minimal coverage of
paginations and the resolve parameter.

#1862 

image

### CODE REVIEW

**Comment by lorawoodford** [comment]
@pobocks - Fun timing. I was just working on adding stuff to resolve #363 today and was getting ready to PR that tomorrow (er... almost today).  Will ping you when that’s ready.

**Comment by pobocks** [comment]
@lorawoodford Thanks! No hurries!

**Comment by lorawoodford** [comment]
Thanks for this @pobocks and it looks good to go.  Instinctually, however, I'm wondering if we should remove the two updated `docs/` files since all of those are essentially throwaway anyway (docs are, at least currently, rebuilt by the program team at release time, so anything in `docs/` is trashed as the first step of that process.  Wondering if the entire directory should be in `.gitignore`.  I may be overcomplicating things, though... do you have thoughts?  Happy to merge this as is, or, if you agree, merge it after the docs files are removed...

**Comment by pobocks** [comment]
Oh, yeah, they're an artifact of my testing process.  I took a sleep aid which is kicking in right now, so if you wanna strip the doc stuff out of the commit, be my guest, otherwise I will try and remember it tomorrow, feel free to poke me about it.

**Comment by pobocks** [comment]
Thanks for getting this!

**Pull request merged**
