### PR TITLE
Use asutils.json_parse over json.parse

### PR DESCRIPTION
**Pull request by cfitz**
This uses the ASUtils.json_parse method over the JSON.parse method.

### CODE REVIEW

**Comment by lmcglohon** [comment]
@pobocks I am trying to understand your comment - should we not be using the ASUtils defined json_parse but rather the JS defined one (the exact opposite of what I believe this PR does)?

**Comment by pobocks** [comment]
As far as I am aware and can determine, ASUtils is _only_ defined in Ruby.  The json_parse that's being replaced is the Ruby stdlib version.  The line I commented on seems to be a replacement of a Javascript JSON.parse (spelled the same but completely distinct from the Ruby one) with ASUtils.json_parse, which doesn't exist in Javascript, only in Ruby.

**Comment by cfitz** [comment]
Ok, sorry took me a few minutes to figure out what you were saying. 
Yes, looks like the refactor was too aggressive. 
I've change it to not include calls to JSON in JS.

**Comment by lmcglohon** [comment]
@cfitz @pobocks We are putting out a release this week, so I expect this to go into the next release which will probably be in the next month or so

**Pull request merged**
