### PR TITLE
Bump jruby and add jrjackson parser

### PR DESCRIPTION
**Pull request by cfitz**
(note this also depends on the #1277 , since jasper used old version of jackson )

This bumps the jruby version to 9.2.0.0. 

It also adds the [jrjackson](https://github.com/guyboertje/jrjackson) gem  that uses the java-based Jackson parser for json. This give a small performance boost across the app, especially when doing lots of json work ( saw a ~15% speed improvement on indexing a rather large collection ). 

Also:

- Updates the version of CSV  gem
- Removes the additional JSON gem from the gemfiles and just use the one that ships with jruby
- Changes some calls to JSON.parse to use the ASUtils.json_parse
- Adds the json initializer ( frontend/config/initializers/json.rb ) included in the frontend app to the public ( improves JSON parsing of large documents )
- removes a weird old file from the frontend initializers (  frontend/config/initializers/javalibs.rb )

### CODE REVIEW

**Comment by cfitz** [comment]
@lmcglohon  Ok, interesting...it looks like jruby 9.2.0.0 doesn't work with java 7. Good to know, I guess...

I can remove jruby upgrade here, if that would work?
But also, might need to drop support for java 7 in the near-ish future?

**Comment by lmcglohon** [comment]
@cfitz Thanks for all of this work! But this pull request has become too large (especially since it includes the commit from #1277) and needs to be split into smaller, self-contained ones in order for them to be reviewed and merged into the core code base.

**Comment by cfitz** [comment]
@lmcglohon yeah, i should have broken these down...
Should I do one with the jruby update or skip that for now?

**Comment by lmcglohon** [comment]
@cfitz maybe skip the jruby update for now.  Once we get the other stuff in, then that can be a separate PR.

**Comment by cfitz** [comment]
broke out into seperate PRs

**Pull request closed without merging**
