### PR TITLE
ANW-373: add siblings in tree directly under selected node in stead of at end

### PR DESCRIPTION
**Pull request by sem42198**
## Description

When adding an archival object, digital object component, or classification term using the 'add sibling' button, the new component will be added directly after the component that was selected when 'add sibling' was initiated rather than at the end of that level.

## Related JIRA Ticket or GitHub Issue

[ANW-373](https://archivesspace.atlassian.net/browse/ANW-373)

## Motivation and Context

Currently, new siblings are always placed at the bottom of the list of siblings, which can be extremely annoying when trying to insert a new object in a long list.

## How Has This Been Tested?

Checked that new siblings now appear after selected node in view and that they are saved here when the record is saved.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by avatar382** [comment]
@sem42198 Thanks for picking this up! I did quite a bit of work on this until getting sidetracked with other tickets.

It looks like you're incrementing the position in your code when inserting a new sibling after another, which is what I initially did -- but then ran into complications. For example: in the code now, siblings position numbers are separated by 1000 when you add a new child. So if you insert object B between objects A (position 1000) and C (position 2000), you'll have:

A (1000)
B (1001)
C (2000)

So not it's not possible to insert a new object between A and B because the position numbers are integers, and there's no longer space on the number line.

I took the approach of halving the distance between the next adjacent sibling, so we'd have something like this:

A (1000)
B (1500)
C (2000)

Which works for about  9 inserts before we have something like this and run out of space. For example, if you insert several siblings after each other, (in order B, D, E, F, G...)  you get something like this, and then you get to a situation where you can't insert more without recalculating all the position numbers.

A (1000)
K (1001)
J (1002)
I (1004)
H (1008)
G (1016)
F (1032)
E (1063)
D (1250)
B (1500)
C (2000)

I discussed this with @lmcglohon and @cdibella, and we decided that we'd want to support at least 30-40 inserts in a row. 

So that means we'd need either to A.) recalculate the position numbers after each insert or B.) Use a really big gap so that most users won't notice this limitation.

This is where I left off on this -- doing some math, I calculated that if we use Bigints for the positions, then we could support a max position number of something like 2^63, which means we can use a step of like 10^12, which supports 40 insertions in a row, and position numbers big enough for around 8 million objects at that humongous step. 

It was wierd to me thinking of position numbers that large, but then again, it's not really different than using really precise decimals to keep track of positions. And maybe recalculating position numbers is a better way to go, but that could lead to performance problems having to do a bunch of database writes for a case where there are a lot of siblings.

Here's a like to my branch with my work on this: https://github.com/avatar382/archivesspace/tree/ANW-373

**Comment by sem42198** [comment]
@avatar382 no problem and thanks for the information! I looked into it and it seems like the re-numbering is being handled for this by the same code that handles it for re-ordering in the tree_nodes mixin though I know there have been some issues with that functionality there which could be a problem here too. It seemed to work correctly in the case I tested it though which was the following scenario:

+----------------+----------------+-----------+----------+
| display_string | root_record_id | parent_id | position |
+----------------+----------------+-----------+----------+
| 1              |             10 |      NULL |     1000 |
| 2              |             10 |      NULL |     1001 |
+----------------+----------------+-----------+----------+

After selecting 1 and adding a sibling it re-numbers the position as follows:

+---------------------+----------------+-----------+----------+
| display_string      | root_record_id | parent_id | position |
+---------------------+----------------+-----------+----------+
| 1                   |             10 |      NULL |     1000 |
| add sibling after 1 |             10 |      NULL |     1500 |
| 2                   |             10 |      NULL |     2001 |
+---------------------+----------------+-----------+----------+

**Comment by avatar382** [comment]
@sem42198 Oh yeah, I remember looking at the re-numbering code. Sounds like your seeing that it's running automatically and updating the position numbers after a position is changed, which is great news. 

When I was working on this, it didn't seem to be doing that and I thought that the renumbering code was only run as part of running the "Enable Reorder mode" function.

**Comment by lorawoodford** [comment]
Also giving this a 👍 Waiting for tests to finish, then merging!

**Pull request merged**
