### PR TITLE
Remove some dead code and use same advance_query_builder as frontend

### PR DESCRIPTION
**Pull request by cfitz**
Starting to wade through some of the code in the public UI, I think this removes some apparently dead code in the controllers/concerns (
debugging and tree_api ).

 This also follows up on the comment left in
the public's
[advance_query_builder](https://github.com/archivesspace/archivesspace/blob/master/public/app/lib/advanced_query_builder.rb#L1-L4)
to use the advance_query_builder in the common directory. Some slight
modifications where made to the Searchable concern to use that version
of the query builder.

### CODE REVIEW

**Comment by lmcglohon** [comment]
@cfitz I just created a release with this branch and am getting an error message when I search through the PUI: 

"Unable to Connect to Database
ArchivesSpace is currently experiencing technical difficulties. We apologise for the inconvenience. Please try again later."

So maybe it isn't completely hooked up to the backend?

**Comment by cfitz** [comment]
Hm, I just did a build and the public UI showed up fine, but the frontend wouldn't let me log in. Kept saying my session expired. Strange...will look at this a bit later.

**Comment by cfitz** [comment]
Ok, I think I figured it out...needed to restart my browser to clear out a bad session. 

I switched the a #empty? to #blank? thinking it would help if a boolean was passed in, but that was a bad idea...I forgot that's a Rails-only method, which won't work in the validation context. 

It shouldn't matter anyway. I added a switch in the advanced_query_builder to turn :value into a string on field_search, which is what the field_search schema wants ( so it should pass the validation ). 

I **think** this works now. But, obviously no rush on this one...

**Comment by lmcglohon** [comment]
@cfitz yep - no longer getting the error.

**Pull request merged**
